"""Tests for ``nauro adopt --remove`` (un-adopt a repo)."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

from typer.testing import CliRunner

from nauro.cli.main import app
from nauro.store.registry import (
    add_repo_v2,
    find_projects_by_name_v2,
    get_store_path_v2,
)
from nauro.store.repo_config import save_repo_config

runner = CliRunner()


def _git_init(repo: Path) -> None:
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)


def _adopt_env(monkeypatch, tmp_path: Path) -> Path:
    """Isolated HOME (diverts ~/.claude, ~/.codex, ~/.agents, ~/.nauro) + a git repo."""
    monkeypatch.setenv("HOME", str(tmp_path))
    repo = tmp_path / "myrepo"
    repo.mkdir()
    _git_init(repo)
    monkeypatch.chdir(repo)
    return repo


def _pid_of(repo: Path) -> str:
    return json.loads((repo / ".nauro" / "config.json").read_text())["id"]


def test_remove_unadopts_repo_and_keeps_store(tmp_path, monkeypatch):
    repo = _adopt_env(monkeypatch, tmp_path)
    assert runner.invoke(app, ["adopt", "--name", "alpha"]).exit_code == 0
    store_path = get_store_path_v2(_pid_of(repo))
    assert store_path.is_dir()
    assert (repo / ".mcp.json").is_file()
    assert (repo / "AGENTS.md").is_file()

    result = runner.invoke(app, ["adopt", "--remove", "--yes"])
    assert result.exit_code == 0, result.output

    # config + registry entry gone
    assert not (repo / ".nauro" / "config.json").exists()
    assert find_projects_by_name_v2("alpha") == []
    # surface wiring + generated AGENTS.md gone (the .mcp.json had only nauro)
    assert not (repo / ".mcp.json").exists()
    assert not (repo / "AGENTS.md").exists()
    # store left intact (D248: never delete decisions as a teardown side effect)
    assert store_path.is_dir()
    assert "store left intact" in result.output


def test_remove_purge_store_deletes_store(tmp_path, monkeypatch):
    repo = _adopt_env(monkeypatch, tmp_path)
    runner.invoke(app, ["adopt", "--name", "alpha"])
    store_path = get_store_path_v2(_pid_of(repo))
    assert store_path.is_dir()

    result = runner.invoke(app, ["adopt", "--remove", "--purge-store", "--yes"])
    assert result.exit_code == 0, result.output
    assert not store_path.exists()
    assert "deleted store" in result.output


def test_remove_on_unadopted_repo_errors(tmp_path, monkeypatch):
    _adopt_env(monkeypatch, tmp_path)  # git repo, never adopted
    result = runner.invoke(app, ["adopt", "--remove", "--yes"])
    assert result.exit_code == 1
    assert "not adopted" in result.output.lower()


def test_remove_strips_generated_agents_md_but_keeps_manual_section(tmp_path, monkeypatch):
    repo = _adopt_env(monkeypatch, tmp_path)
    runner.invoke(app, ["adopt", "--name", "alpha"])
    agents = repo / "AGENTS.md"
    # Edit the existing (generated-empty) # Manual section, the way a user would:
    # add notes under the header that sits above the attribution footer.
    content = agents.read_text()
    assert "# Manual\n" in content
    assert "## Project:" in content  # generated payload present before teardown
    agents.write_text(content.replace("# Manual\n", "# Manual\n\nMy own notes.\n", 1))

    result = runner.invoke(app, ["adopt", "--remove", "--yes"])
    assert result.exit_code == 0, result.output
    assert agents.is_file()
    text = agents.read_text()
    # User notes preserved...
    assert "My own notes." in text
    # ...but all Nauro-generated content is gone (no stale "use Nauro MCP" lines).
    assert "## Project:" not in text
    assert "Generated by [Nauro]" not in text
    assert "stripped generated AGENTS.md" in result.output


def test_remove_aborts_on_declined_confirmation(tmp_path, monkeypatch):
    repo = _adopt_env(monkeypatch, tmp_path)
    runner.invoke(app, ["adopt", "--name", "alpha"])

    result = runner.invoke(app, ["adopt", "--remove"], input="n\n")
    assert result.exit_code != 0  # typer.confirm(abort=True)
    # Nothing torn down.
    assert (repo / ".nauro" / "config.json").exists()
    assert find_projects_by_name_v2("alpha") != []
    assert (repo / ".mcp.json").is_file()


def test_remove_purge_store_refused_when_other_repos_remain(tmp_path, monkeypatch):
    monkeypatch.setenv("HOME", str(tmp_path))
    repo_a = tmp_path / "repoA"
    repo_a.mkdir()
    _git_init(repo_a)
    repo_b = tmp_path / "repoB"
    repo_b.mkdir()
    _git_init(repo_b)
    monkeypatch.chdir(repo_a)
    assert runner.invoke(app, ["adopt", "--name", "multi"]).exit_code == 0
    pid = _pid_of(repo_a)
    add_repo_v2(pid, repo_b)
    save_repo_config(repo_b, {"mode": "local", "id": pid, "name": "multi"})

    result = runner.invoke(
        app, ["adopt", "--remove", "--purge-store", "--yes", "--repo", str(repo_a)]
    )
    assert result.exit_code == 1
    assert "purge-store refused" in result.output.lower()
    # Untouched: still adopted, store intact.
    assert (repo_a / ".nauro" / "config.json").exists()
    assert get_store_path_v2(pid).is_dir()


def test_remove_multi_repo_drops_only_this_repo_and_keeps_shared_scope(tmp_path, monkeypatch):
    monkeypatch.setenv("HOME", str(tmp_path))
    repo_a = tmp_path / "repoA"
    repo_a.mkdir()
    _git_init(repo_a)
    repo_b = tmp_path / "repoB"
    repo_b.mkdir()
    _git_init(repo_b)
    monkeypatch.chdir(repo_a)
    assert runner.invoke(app, ["adopt", "--name", "multi"]).exit_code == 0
    pid = _pid_of(repo_a)
    add_repo_v2(pid, repo_b)
    save_repo_config(repo_b, {"mode": "local", "id": pid, "name": "multi"})
    store_path = get_store_path_v2(pid)

    # adopt wired the shared, user-global Codex entry.
    codex_cfg = tmp_path / ".codex" / "config.toml"
    assert codex_cfg.is_file()
    assert "nauro" in codex_cfg.read_text()

    result = runner.invoke(app, ["adopt", "--remove", "--yes", "--repo", str(repo_a)])
    assert result.exit_code == 0, result.output

    # repo_a torn down...
    assert not (repo_a / ".nauro" / "config.json").exists()
    # ...but the project survives with repo_b, store intact.
    matches = find_projects_by_name_v2("multi")
    assert len(matches) == 1
    _id, entry = matches[0]
    paths = {str(Path(p).resolve()) for p in entry["repo_paths"]}
    assert str(repo_b.resolve()) in paths
    assert str(repo_a.resolve()) not in paths
    assert store_path.is_dir()
    # repo_b's per-repo config untouched.
    assert (repo_b / ".nauro" / "config.json").exists()
    # Shared user-scope (Codex entry) preserved because repo_b still depends on it.
    assert codex_cfg.is_file()
    assert "nauro" in codex_cfg.read_text()


def test_remove_rejects_add_path_flags(tmp_path, monkeypatch):
    repo = _adopt_env(monkeypatch, tmp_path)
    runner.invoke(app, ["adopt", "--name", "alpha"])
    result = runner.invoke(app, ["adopt", "--remove", "--with-subagents", "--yes"])
    assert result.exit_code == 1
    assert "cannot be combined" in result.output
    assert (repo / ".nauro" / "config.json").exists()


def test_purge_store_requires_remove(tmp_path, monkeypatch):
    _adopt_env(monkeypatch, tmp_path)
    result = runner.invoke(app, ["adopt", "--purge-store"])
    assert result.exit_code == 1
    assert "requires --remove" in result.output
