"""Tests for the Claude Code CLAUDE.md bridge.

The bridge is an auto-written, Nauro-owned, thin CLAUDE.md whose only
context-visible content is an ``@AGENTS.md`` import - the one artifact that
makes Nauro's generated AGENTS.md load in an otherwise-unwired Claude Code
session. These tests pin the pure detector (fence/inline-span/BOM aware and
ownership by the exact marker line), the write/keep/advise/refuse/failure
policy, the byte-preserving ownership-gated teardown, and the wiring into the
shared AGENTS.md-regen seam (setup / adopt / sync / init), including the
no-oscillation guarantee against the legacy block cleanup.

The expected bridge file bytes are written out as a literal here on purpose:
any production wording or newline change must fail this suite, not silently
agree with an imported constant.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest
from typer.testing import CliRunner

from nauro.cli.integrations.claude_bridge import (
    BRIDGE_IMPORT,
    BridgeState,
    detect_bridge_state,
    ensure_claude_bridge,
    remove_claude_bridge,
)
from nauro.cli.integrations.legacy import CLAUDE_MD_END, CLAUDE_MD_START, _remove_claude_md
from nauro.cli.integrations.outcomes import BridgeKind
from nauro.cli.main import app
from nauro.constants import CLAUDE_BRIDGE_MARKER, CLAUDE_MD
from nauro.mcp.tools import tool_propose_decision
from nauro.store.registry import register_project_v2
from nauro.store.repo_config import save_repo_config
from nauro.templates.scaffolds import scaffold_project_store

runner = CliRunner()

# The exact bytes the bridge writes, spelled out (not imported) so a wording or
# newline drift in production fails here.
EXPECTED_BRIDGE = (
    "<!-- nauro-claude-bridge: auto-generated by Nauro. Imports AGENTS.md so "
    "Claude Code loads the shared project context (Claude Code does not read "
    "AGENTS.md natively). Managed by nauro; remove with 'nauro adopt --remove'. -->\n"
    "@AGENTS.md\n"
)
MARKER_LINE = EXPECTED_BRIDGE.splitlines()[0]


def _repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    return repo


def _write(repo: Path, content: str) -> None:
    (repo / CLAUDE_MD).write_text(content, encoding="utf-8")


# ─── detector matrix ─────────────────────────────────────────────────────────


def test_detect_absent(tmp_path: Path):
    assert detect_bridge_state(_repo(tmp_path)) is BridgeState.ABSENT


def test_detect_owned(tmp_path: Path):
    repo = _repo(tmp_path)
    _write(repo, EXPECTED_BRIDGE)
    assert detect_bridge_state(repo) is BridgeState.OWNED


def test_detect_owned_with_user_additions(tmp_path: Path):
    repo = _repo(tmp_path)
    _write(repo, EXPECTED_BRIDGE + "\n# My notes\n")
    assert detect_bridge_state(repo) is BridgeState.OWNED


def test_detect_foreign_bridged_live_import(tmp_path: Path):
    repo = _repo(tmp_path)
    _write(repo, "# My project\n\n@AGENTS.md\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_BRIDGED


def test_detect_foreign_bridged_inline_prose(tmp_path: Path):
    repo = _repo(tmp_path)
    _write(repo, "See @AGENTS.md for the shared context.\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_BRIDGED


def test_detect_foreign_unbridged_plain(tmp_path: Path):
    repo = _repo(tmp_path)
    _write(repo, "# My project\n\nSome instructions.\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_UNBRIDGED


def test_token_mention_without_marker_line_is_not_owned(tmp_path: Path):
    """A hand-written file that only mentions the token is foreign, not owned."""
    repo = _repo(tmp_path)
    _write(repo, f"# Notes\n\nWe used to carry a {CLAUDE_BRIDGE_MARKER} marker here.\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_UNBRIDGED


def test_token_mention_with_live_import_is_foreign_bridged(tmp_path: Path):
    repo = _repo(tmp_path)
    _write(repo, f"# Notes about {CLAUDE_BRIDGE_MARKER}\n\n@AGENTS.md\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_BRIDGED


def test_marker_line_inside_fence_is_not_owned(tmp_path: Path):
    """The exact marker line quoted inside a code fence is not active ownership."""
    repo = _repo(tmp_path)
    _write(repo, f"# Docs\n\n```\n{MARKER_LINE}\n```\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_UNBRIDGED


def test_import_inside_backtick_fence_is_not_live(tmp_path: Path):
    repo = _repo(tmp_path)
    _write(repo, "# Docs\n\n```\n@AGENTS.md\n```\n\nNo live import here.\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_UNBRIDGED


def test_import_inside_tilde_fence_is_not_live(tmp_path: Path):
    repo = _repo(tmp_path)
    _write(repo, "~~~\n@AGENTS.md\n~~~\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_UNBRIDGED


def test_tilde_does_not_close_a_backtick_fence(tmp_path: Path):
    """A ~~~ line inside a ``` fence is content, so the import stays fenced."""
    repo = _repo(tmp_path)
    _write(repo, "```\n~~~\n@AGENTS.md\n```\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_UNBRIDGED


def test_shorter_run_does_not_close_a_longer_fence(tmp_path: Path):
    """A 3-backtick line does not close a 4-backtick fence."""
    repo = _repo(tmp_path)
    _write(repo, "````\n```\n@AGENTS.md\n````\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_UNBRIDGED


def test_import_after_closed_fence_is_live(tmp_path: Path):
    repo = _repo(tmp_path)
    _write(repo, "```\ncode\n```\n\n@AGENTS.md\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_BRIDGED


def test_import_live_and_also_fenced_counts_as_live(tmp_path: Path):
    repo = _repo(tmp_path)
    _write(repo, "@AGENTS.md\n\n```\n@AGENTS.md\n```\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_BRIDGED


def test_import_inside_single_backtick_span_is_not_live(tmp_path: Path):
    repo = _repo(tmp_path)
    _write(repo, "Write `@AGENTS.md` to import context.\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_UNBRIDGED


def test_import_inside_double_backtick_span_is_not_live(tmp_path: Path):
    """A code span opened by a run of two backticks closes on two backticks."""
    repo = _repo(tmp_path)
    _write(repo, "Use `` @AGENTS.md `` in a span.\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_UNBRIDGED


def test_import_after_unmatched_backtick_is_live(tmp_path: Path):
    """An unmatched backtick is literal text, so a later import stays live."""
    repo = _repo(tmp_path)
    _write(repo, "a ` b @AGENTS.md\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_BRIDGED


def test_bom_prefixed_live_import_is_recognized(tmp_path: Path):
    repo = _repo(tmp_path)
    (repo / CLAUDE_MD).write_bytes(b"\xef\xbb\xbf@AGENTS.md\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_BRIDGED


def test_bom_prefixed_owned_bridge_is_recognized(tmp_path: Path):
    repo = _repo(tmp_path)
    (repo / CLAUDE_MD).write_bytes(b"\xef\xbb\xbf" + EXPECTED_BRIDGE.encode("utf-8"))
    assert detect_bridge_state(repo) is BridgeState.OWNED


@pytest.mark.skipif(os.name == "nt", reason="symlink creation requires extra Windows privileges")
def test_detect_symlink(tmp_path: Path):
    repo = _repo(tmp_path)
    outside = tmp_path / "outside.md"
    outside.write_text("whatever\n", encoding="utf-8")
    (repo / CLAUDE_MD).symlink_to(outside)
    assert detect_bridge_state(repo) is BridgeState.SYMLINK


# ─── ensure ──────────────────────────────────────────────────────────────────


def test_ensure_writes_byte_exact_on_absent(tmp_path: Path):
    repo = _repo(tmp_path)

    outcome = ensure_claude_bridge(repo)

    assert outcome.kind is BridgeKind.WROTE
    # Against the inlined literal, not an imported constant.
    assert (repo / CLAUDE_MD).read_bytes() == EXPECTED_BRIDGE.encode("utf-8")


def test_ensure_content_is_ascii_only(tmp_path: Path):
    repo = _repo(tmp_path)
    ensure_claude_bridge(repo)
    (repo / CLAUDE_MD).read_bytes().decode("ascii")


def test_ensure_idempotent_on_owned(tmp_path: Path):
    repo = _repo(tmp_path)
    ensure_claude_bridge(repo)
    before = (repo / CLAUDE_MD).read_bytes()

    outcome = ensure_claude_bridge(repo)

    assert outcome.kind is BridgeKind.KEPT
    assert (repo / CLAUDE_MD).read_bytes() == before


def test_ensure_keeps_user_additions_on_owned(tmp_path: Path):
    repo = _repo(tmp_path)
    body = EXPECTED_BRIDGE + "\n# My extra Claude Code instructions\n"
    _write(repo, body)

    outcome = ensure_claude_bridge(repo)

    assert outcome.kind is BridgeKind.KEPT
    assert (repo / CLAUDE_MD).read_text(encoding="utf-8") == body


def test_ensure_silent_on_foreign_bridged(tmp_path: Path):
    repo = _repo(tmp_path)
    original = "# My project\n\n@AGENTS.md\n"
    _write(repo, original)

    outcome = ensure_claude_bridge(repo)

    assert outcome.kind is BridgeKind.FOREIGN_PRESENT
    assert (repo / CLAUDE_MD).read_text(encoding="utf-8") == original


def test_ensure_advises_on_foreign_unbridged_without_modifying(tmp_path: Path):
    repo = _repo(tmp_path)
    original = "# My project\n\nInstructions with no import.\n"
    _write(repo, original)

    outcome = ensure_claude_bridge(repo)

    assert outcome.kind is BridgeKind.ADVISORY
    assert (repo / CLAUDE_MD).read_text(encoding="utf-8") == original


def test_ensure_reports_failure_when_claude_md_is_a_directory(tmp_path: Path):
    """A directory at the CLAUDE.md path is a typed failure, never a raise."""
    repo = _repo(tmp_path)
    (repo / CLAUDE_MD).mkdir()

    outcome = ensure_claude_bridge(repo)

    assert outcome.kind is BridgeKind.FAILED
    assert outcome.detail is not None
    assert (repo / CLAUDE_MD).is_dir()


@pytest.mark.skipif(os.name == "nt", reason="symlink creation requires extra Windows privileges")
def test_ensure_refuses_symlink(tmp_path: Path):
    repo = _repo(tmp_path)
    outside = tmp_path / "outside.md"
    outside.write_text("untouchable\n", encoding="utf-8")
    (repo / CLAUDE_MD).symlink_to(outside)

    outcome = ensure_claude_bridge(repo)

    assert outcome.kind is BridgeKind.REFUSED_SYMLINK
    assert (repo / CLAUDE_MD).is_symlink()
    assert outside.read_text(encoding="utf-8") == "untouchable\n"


# ─── remove ──────────────────────────────────────────────────────────────────


def test_remove_unlinks_pure_bridge(tmp_path: Path):
    repo = _repo(tmp_path)
    ensure_claude_bridge(repo)

    outcome = remove_claude_bridge(repo)

    assert outcome.kind is BridgeKind.REMOVED
    assert not (repo / CLAUDE_MD).exists()


def test_remove_strips_only_bridge_lines_when_user_appended(tmp_path: Path):
    repo = _repo(tmp_path)
    _write(repo, EXPECTED_BRIDGE + "\n# My notes\n\nKeep these.\n")

    outcome = remove_claude_bridge(repo)

    assert outcome.kind is BridgeKind.STRIPPED
    content = (repo / CLAUDE_MD).read_text(encoding="utf-8")
    assert CLAUDE_BRIDGE_MARKER not in content
    assert BRIDGE_IMPORT not in content.split()
    assert "# My notes" in content
    assert "Keep these." in content


def test_remove_tolerates_blank_line_between_marker_and_import(tmp_path: Path):
    repo = _repo(tmp_path)
    _write(repo, f"{MARKER_LINE}\n\n{BRIDGE_IMPORT}\n\n# Kept\n")

    outcome = remove_claude_bridge(repo)

    assert outcome.kind is BridgeKind.STRIPPED
    content = (repo / CLAUDE_MD).read_text(encoding="utf-8")
    assert BRIDGE_IMPORT not in content.split()
    assert "# Kept" in content


def test_remove_byte_preserves_user_crlf_and_trailing_whitespace(tmp_path: Path):
    """User content keeps its CRLF endings and trailing whitespace verbatim."""
    repo = _repo(tmp_path)
    user = "# Title\r\ntrailing spaces here   \r\nlast line no newline"
    (repo / CLAUDE_MD).write_bytes(EXPECTED_BRIDGE.encode("utf-8") + user.encode("utf-8"))

    outcome = remove_claude_bridge(repo)

    assert outcome.kind is BridgeKind.STRIPPED
    assert (repo / CLAUDE_MD).read_bytes() == user.encode("utf-8")


def test_remove_leaves_foreign_file_untouched(tmp_path: Path):
    repo = _repo(tmp_path)
    original = "# My project\n\n@AGENTS.md\n"
    _write(repo, original)

    outcome = remove_claude_bridge(repo)

    assert outcome.kind is BridgeKind.NOTHING_TO_REMOVE
    assert (repo / CLAUDE_MD).read_text(encoding="utf-8") == original


def test_remove_leaves_token_mention_untouched(tmp_path: Path):
    """A file that only mentions the token (no exact marker line) is not ours."""
    repo = _repo(tmp_path)
    original = f"# Notes\n\nmentions {CLAUDE_BRIDGE_MARKER} but is not the bridge.\n"
    _write(repo, original)

    outcome = remove_claude_bridge(repo)

    assert outcome.kind is BridgeKind.NOTHING_TO_REMOVE
    assert (repo / CLAUDE_MD).read_text(encoding="utf-8") == original


def test_remove_noop_when_absent(tmp_path: Path):
    outcome = remove_claude_bridge(_repo(tmp_path))
    assert outcome.kind is BridgeKind.NOTHING_TO_REMOVE


def test_remove_reports_failure_when_claude_md_is_a_directory(tmp_path: Path):
    repo = _repo(tmp_path)
    (repo / CLAUDE_MD).mkdir()

    outcome = remove_claude_bridge(repo)

    assert outcome.kind is BridgeKind.FAILED
    assert (repo / CLAUDE_MD).is_dir()


@pytest.mark.skipif(os.name == "nt", reason="symlink creation requires extra Windows privileges")
def test_remove_refuses_symlink(tmp_path: Path):
    repo = _repo(tmp_path)
    outside = tmp_path / "outside.md"
    outside.write_text(EXPECTED_BRIDGE, encoding="utf-8")
    (repo / CLAUDE_MD).symlink_to(outside)

    outcome = remove_claude_bridge(repo)

    assert outcome.kind is BridgeKind.REFUSED_SYMLINK
    assert (repo / CLAUDE_MD).is_symlink()
    assert outside.read_text(encoding="utf-8") == EXPECTED_BRIDGE


# ─── no oscillation with the legacy NAURO block cleanup ──────────────────────


def test_legacy_cleanup_never_strips_the_bridge(tmp_path: Path):
    """``_remove_claude_md`` targets the NAURO:START/END block, never the bridge."""
    repo = _repo(tmp_path)
    ensure_claude_bridge(repo)
    before = (repo / CLAUDE_MD).read_bytes()

    assert _remove_claude_md(repo) is None
    assert (repo / CLAUDE_MD).read_bytes() == before
    assert detect_bridge_state(repo) is BridgeState.OWNED


def test_setup_claude_code_twice_keeps_bridge_stable(tmp_path: Path, monkeypatch):
    repo = tmp_path / "repo"
    repo.mkdir()
    pid, store = register_project_v2("proj", [repo])
    scaffold_project_store("proj", store)
    save_repo_config(repo, {"mode": "local", "id": pid, "name": "proj"})
    monkeypatch.chdir(repo)

    first = runner.invoke(app, ["setup", "claude-code"])
    assert first.exit_code == 0
    bridge_bytes = (repo / CLAUDE_MD).read_bytes()

    second = runner.invoke(app, ["setup", "claude-code"])
    assert second.exit_code == 0

    # The bridge survives a second run byte-for-byte, and the transcript is
    # stable (no oscillation between legacy cleanup and the bridge write).
    assert (repo / CLAUDE_MD).read_bytes() == bridge_bytes
    assert second.stdout == first.stdout


def test_legacy_block_stripped_then_treated_as_foreign_unbridged(tmp_path: Path, monkeypatch):
    """A CLAUDE.md carrying a legacy block keeps its remainder, advised not clobbered."""
    repo = tmp_path / "repo"
    repo.mkdir()
    pid, store = register_project_v2("proj", [repo])
    scaffold_project_store("proj", store)
    save_repo_config(repo, {"mode": "local", "id": pid, "name": "proj"})
    monkeypatch.chdir(repo)
    original_remainder = "# My project\n\nKeep this.\n"
    _write(repo, f"{original_remainder}\n{CLAUDE_MD_START}\nold block\n{CLAUDE_MD_END}\n")

    result = runner.invoke(app, ["setup", "claude-code"])
    assert result.exit_code == 0

    content = (repo / CLAUDE_MD).read_text(encoding="utf-8")
    assert CLAUDE_MD_START not in content
    assert "# My project" in content
    assert "Keep this." in content
    # The remainder has no import and no bridge marker: it stays foreign and is
    # never rewritten into an owned bridge.
    assert CLAUDE_BRIDGE_MARKER not in content
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_UNBRIDGED


# ─── dogfood: a hand-authored CLAUDE.md is preserved across setup/sync ────────


def test_hand_authored_claude_md_survives_setup_all(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("HOME", str(tmp_path / "home"))
    repo = tmp_path / "repo"
    repo.mkdir()
    pid, store = register_project_v2("proj", [repo])
    scaffold_project_store("proj", store)
    save_repo_config(repo, {"mode": "local", "id": pid, "name": "proj"})
    monkeypatch.chdir(repo)
    handwritten = "# CLAUDE.md\n\nMonorepo instructions the user maintains by hand.\n"
    _write(repo, handwritten)

    result = runner.invoke(app, ["setup", "all"])
    assert result.exit_code == 0

    # Byte-identical, and the advisory names the one-line fix.
    assert (repo / CLAUDE_MD).read_text(encoding="utf-8") == handwritten
    assert "add '@AGENTS.md'" in result.stdout


# ─── integration: the shared regen seam covers every AGENTS.md write ─────────


def test_setup_all_writes_bridge(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("HOME", str(tmp_path / "home"))
    repo = tmp_path / "repo"
    repo.mkdir()
    pid, store = register_project_v2("proj", [repo])
    scaffold_project_store("proj", store)
    save_repo_config(repo, {"mode": "local", "id": pid, "name": "proj"})
    monkeypatch.chdir(repo)

    result = runner.invoke(app, ["setup", "all"])
    assert result.exit_code == 0

    assert (repo / CLAUDE_MD).read_bytes() == EXPECTED_BRIDGE.encode("utf-8")
    assert "CLAUDE.md imports AGENTS.md (Claude Code bridge)" in result.stdout


def test_setup_all_remove_deletes_bridge(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("HOME", str(tmp_path / "home"))
    repo = tmp_path / "repo"
    repo.mkdir()
    pid, store = register_project_v2("proj", [repo])
    scaffold_project_store("proj", store)
    save_repo_config(repo, {"mode": "local", "id": pid, "name": "proj"})
    monkeypatch.chdir(repo)
    assert runner.invoke(app, ["setup", "all"]).exit_code == 0
    assert (repo / CLAUDE_MD).exists()

    result = runner.invoke(app, ["setup", "all", "--remove"])
    assert result.exit_code == 0

    assert not (repo / CLAUDE_MD).exists()
    assert "removed CLAUDE.md bridge" in result.stdout


def test_init_writes_bridge_at_the_regen_seam(tmp_path: Path, monkeypatch):
    """init regenerates AGENTS.md, so the shared seam ensures the bridge too."""
    repo = tmp_path / "repo"
    repo.mkdir()

    result = runner.invoke(app, ["init", "proj", "--add-repo", str(repo)])
    assert result.exit_code == 0

    assert (repo / "AGENTS.md").is_file()
    assert (repo / CLAUDE_MD).read_bytes() == EXPECTED_BRIDGE.encode("utf-8")


def test_sync_multi_repo_bridges_every_repo(tmp_path: Path, monkeypatch):
    repo1 = tmp_path / "repo1"
    repo2 = tmp_path / "repo2"
    repo1.mkdir()
    repo2.mkdir()
    _pid, store = register_project_v2("multi", [repo1, repo2])
    scaffold_project_store("multi", store)
    monkeypatch.chdir(repo1)

    result = runner.invoke(app, ["sync"])
    assert result.exit_code == 0

    assert (repo1 / CLAUDE_MD).read_bytes() == EXPECTED_BRIDGE.encode("utf-8")
    assert (repo2 / CLAUDE_MD).read_bytes() == EXPECTED_BRIDGE.encode("utf-8")
    bridge_lines = [
        line
        for line in result.stdout.splitlines()
        if "CLAUDE.md imports AGENTS.md (Claude Code bridge)" in line
    ]
    assert len(bridge_lines) == 2


def test_sync_continues_when_one_repo_has_a_broken_claude_md(tmp_path: Path, monkeypatch):
    """A directory at one repo's CLAUDE.md path is reported, and the loop goes on."""
    repo1 = tmp_path / "repo1"
    repo2 = tmp_path / "repo2"
    repo1.mkdir()
    repo2.mkdir()
    (repo1 / CLAUDE_MD).mkdir()  # broken: a directory where the bridge would go
    _pid, store = register_project_v2("multi", [repo1, repo2])
    scaffold_project_store("multi", store)
    monkeypatch.chdir(repo2)

    result = runner.invoke(app, ["sync"])
    assert result.exit_code == 0

    # repo1's failure is surfaced, repo1 is left as a directory, and repo2 is
    # still bridged - the loop did not abort on the bad repo.
    assert "CLAUDE.md bridge error" in result.stdout
    assert (repo1 / CLAUDE_MD).is_dir()
    assert (repo2 / CLAUDE_MD).read_bytes() == EXPECTED_BRIDGE.encode("utf-8")


# ─── review-round pins ───────────────────────────────────────────────────────


def test_remove_byte_preserves_invalid_utf8_user_content(tmp_path: Path):
    """User bytes that are not valid UTF-8 survive teardown byte-for-byte."""
    repo = _repo(tmp_path)
    user = b"user notes:\xff and more\n"
    (repo / CLAUDE_MD).write_bytes(EXPECTED_BRIDGE.encode("utf-8") + user)

    outcome = remove_claude_bridge(repo)

    assert outcome.kind is BridgeKind.STRIPPED
    assert (repo / CLAUDE_MD).read_bytes() == user


def test_remove_keeps_fenced_bridge_copy_in_user_content(tmp_path: Path):
    """Only the real top-level bridge is removed; a fenced copy survives."""
    repo = _repo(tmp_path)
    fenced_copy = f"\n# User docs\n\n```\n{MARKER_LINE}\n{BRIDGE_IMPORT}\n```\n"
    (repo / CLAUDE_MD).write_bytes((EXPECTED_BRIDGE + fenced_copy).encode("utf-8"))

    outcome = remove_claude_bridge(repo)

    assert outcome.kind is BridgeKind.STRIPPED
    # The real bridge span is gone; the fenced example is byte-identical.
    assert (repo / CLAUDE_MD).read_bytes() == fenced_copy.encode("utf-8")
    # The remaining marker is only inside a fence, so the file is no longer owned.
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_UNBRIDGED


def test_backtick_fence_info_string_with_backtick_is_not_a_fence(tmp_path: Path):
    """A backtick fence opener whose info string holds a backtick is not a fence,
    so a later top-level import is still live."""
    repo = _repo(tmp_path)
    _write(repo, "```foo`bar\n@AGENTS.md\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_BRIDGED


def test_import_on_second_line_of_multiline_span_is_live_by_design(tmp_path: Path):
    """A CommonMark inline code span can cross lines, but the scanner is
    line-based on purpose (scanner-safety-first: a stray earlier backtick can
    never poison the marker-line match, and the failure direction is only a
    suppressed advisory with no write). Pin the current behavior: an import on
    the second line of a would-be multi-line span reads as live."""
    repo = _repo(tmp_path)
    _write(repo, "text `open\n@AGENTS.md close`\n")
    assert detect_bridge_state(repo) is BridgeState.FOREIGN_BRIDGED


def test_note_surfaces_bridge_advisory_for_unbridged_claude_md(tmp_path: Path, monkeypatch):
    """A sink-less CLI caller (note) surfaces the advisory through its warn channel."""
    repo = tmp_path / "repo"
    repo.mkdir()
    pid, store = register_project_v2("proj", [repo])
    scaffold_project_store("proj", store)
    save_repo_config(repo, {"mode": "local", "id": pid, "name": "proj"})
    monkeypatch.chdir(repo)
    handwritten = "# My project\n\nHand-written, no import.\n"
    _write(repo, handwritten)

    result = runner.invoke(app, ["note", "We will store all API timestamps in UTC."])
    assert result.exit_code == 0

    # The advisory (the whole remedy for FOREIGN_UNBRIDGED) reaches the user, and
    # the foreign file is not modified.
    assert "add '@AGENTS.md'" in result.output
    assert (repo / CLAUDE_MD).read_text(encoding="utf-8") == handwritten


@pytest.mark.skipif(os.name == "nt", reason="symlink creation requires extra Windows privileges")
def test_note_surfaces_bridge_symlink_refusal(tmp_path: Path, monkeypatch):
    """A sink-less CLI caller (note) surfaces the bridge symlink refusal too."""
    repo = tmp_path / "repo"
    repo.mkdir()
    pid, store = register_project_v2("proj", [repo])
    scaffold_project_store("proj", store)
    save_repo_config(repo, {"mode": "local", "id": pid, "name": "proj"})
    monkeypatch.chdir(repo)
    outside = tmp_path / "outside.md"
    outside.write_text("untouchable\n", encoding="utf-8")
    (repo / CLAUDE_MD).symlink_to(outside)

    result = runner.invoke(app, ["note", "We will store all API timestamps in UTC."])
    assert result.exit_code == 0

    # The refusal reaches the CLI warn channel instead of vanishing, and the
    # symlink is never written through.
    assert "refused to modify" in result.output
    assert "it is a symlink" in result.output
    assert (repo / CLAUDE_MD).is_symlink()
    assert outside.read_text(encoding="utf-8") == "untouchable\n"


def test_mcp_propose_decision_stays_silent_about_bridge(tmp_path: Path, monkeypatch):
    """The stdio MCP write path ensures the bridge but narrates nothing about it."""
    repo = tmp_path / "repo"
    repo.mkdir()
    pid, store = register_project_v2("proj", [repo])
    scaffold_project_store("proj", store)
    save_repo_config(repo, {"mode": "local", "id": pid, "name": "proj"})
    _write(repo, "# My project\n\nHand-written, no import.\n")

    response = tool_propose_decision(
        store,
        title="Store API timestamps in UTC",
        rationale="Storing every timestamp in UTC avoids timezone drift across services.",
        confidence="high",
    )

    assert response["status"] == "confirmed"
    # The seam ran (AGENTS.md regenerated) but the bridge advisory never leaks
    # into the protocol response.
    assert (repo / "AGENTS.md").is_file()
    assert "@AGENTS.md" not in response.get("assessment", "")
    assert "CLAUDE.md" not in str(response)
