"""Tests for AGENTS.md generation and sync integration."""

from pathlib import Path

from nauro_core.constants import MCP_INSTRUCTIONS_STATIC
from nauro_core.protocol import _APPROVAL_BEFORE_PROPOSE
from typer.testing import CliRunner

from nauro.cli.main import app
from nauro.templates.agents_md import (
    READ_TOOL_ROWS,
    WRITE_TOOL_ROWS,
    generate_agents_md,
)
from nauro.templates.scaffolds import scaffold_project_store

runner = CliRunner()


# --- generate_agents_md ---


def test_generate_includes_all_sections():
    result = generate_agents_md("myproj", "State and decisions here")
    assert "# AGENTS.md" in result
    assert "Auto-generated by Nauro" in result
    assert "Do not edit above the Manual section" in result
    assert "## Project: myproj" in result
    assert "State and decisions here" in result
    assert "## Nauro MCP Tools" in result
    # Anchor to the rendered signature (backtick + open paren) so a stray
    # mention of the tool name in prose can't make these assertions pass.
    assert "`get_context(" in result
    assert "`propose_decision(" in result
    assert "`flag_question(" in result
    assert "`update_state(" in result
    assert "# Manual" in result
    assert "Generated by [Nauro]" in result


def test_generate_includes_behavioral_instructions():
    result = generate_agents_md("myproj", "payload")
    public_artifacts_rule = (
        "**Keep public-facing artifacts public.** Paraphrase Nauro rationale instead of\n"
        "citing raw decision or question ids. Internal planning and review may cite ids."
    )
    assert "When to use these tools" in result
    assert "When to propose decisions" in result
    assert "Flag a question" in result
    assert "Update state" in result
    assert result.count(public_artifacts_rule) == 1
    assert "surface related decisions without writing" in result
    assert "complete add, update, or supersede draft" in result
    assert "explicit user approval" in result
    assert result.count(_APPROVAL_BEFORE_PROPOSE) == 1
    assert "commits immediately after validation" in result
    assert "advisory conflict checks" not in result


def test_generate_frontloads_canonical_preflight_before_l0_payload():
    l0_payload = "**One-liner:** Stable project scope.\n\n## Current State\n\nActive work."
    result = generate_agents_md("myproj", l0_payload)

    expected = f"{MCP_INSTRUCTIONS_STATIC}\n\n## Project: myproj\n\n{l0_payload}\n"
    assert expected in result
    assert result.count(MCP_INSTRUCTIONS_STATIC) == 1


def test_generated_footer_names_human_ratified_judgment():
    result = generate_agents_md("myproj", "payload")
    assert "from human-ratified project judgment" in result
    assert result.count("*Generated by [Nauro](") == 1


def test_routing_block_steers_to_local_stdio_with_project_id():
    """The store-routing block names the local tools and the id to pass."""
    result = generate_agents_md("myproj", "payload", project_id="01ABCXYZ")
    assert "## Nauro store for this repo" in result
    assert "`mcp__nauro__*`" in result
    assert "project_id: 01ABCXYZ" in result
    # Names the cloud connector only to steer away from it for this repo.
    assert "mcp__claude_ai_Nauro__*" in result


def test_routing_block_omits_project_id_line_when_unknown():
    """Legacy v1 projects have no id — the block still steers to local, no id line."""
    result = generate_agents_md("myproj", "payload")
    assert "## Nauro store for this repo" in result
    assert "`mcp__nauro__*`" in result
    assert "project_id:" not in result


def test_routing_block_scopes_cloud_connector_name_to_subagents():
    """The cloud-connector `Nauro` name is required for the bundled Claude Code
    subagents; other tools (Codex/Cursor) may use any distinct name."""
    result = generate_agents_md("myproj", "payload")
    assert "exactly `Nauro`" in result
    assert "`@nauro-*`" in result
    assert "`mcp__claude_ai_Nauro__*`" in result
    assert "Codex" in result


def test_check_decision_categorized_as_read_tool():
    """check_decision is a read-only tool — it must not appear under Write tools.

    Guards the categorization fix landed alongside the stale-setup-docs PR.
    """
    result = generate_agents_md("myproj", "payload")
    read_idx = result.index("**Read tools")
    write_idx = result.index("**Write tools")
    behavioral_idx = result.index("### When to use these tools")
    read_block = result[read_idx:write_idx]
    write_block = result[write_idx:behavioral_idx]
    assert "check_decision" in read_block
    assert "check_decision(" not in write_block


def test_tool_counts_derived_from_row_catalogs():
    """Section counts must always match list lengths — no hardcoded numbers."""
    result = generate_agents_md("myproj", "payload")
    read_count = len(READ_TOOL_ROWS)
    write_count = len(WRITE_TOOL_ROWS)
    total = read_count + write_count
    assert f"these {total} tools are available" in result
    assert f"**Read tools ({read_count}):**" in result
    assert f"**Write tools ({write_count}):**" in result


def test_tools_lead_line_covers_no_mcp_agents():
    """The tools section tells MCP-less agents about the CLI mirror."""
    result = generate_agents_md("myproj", "payload")
    assert (
        "without MCP, the same tools work as `nauro <tool-name>` shell commands "
        "(e.g. `nauro check-decision`)."
    ) in result


def test_generate_with_manual_section():
    result = generate_agents_md("proj", "payload", manual_section="Use conventional commits.\n")
    assert "# Manual" in result
    assert "Use conventional commits." in result


def test_generate_without_manual_section():
    result = generate_agents_md("proj", "payload", manual_section=None)
    assert "# Manual\n" in result
    # After Manual header, only the footer remains
    idx = result.index("# Manual\n")
    after = result[idx + len("# Manual\n") :]
    assert "Generated by" in after
    # No other content between Manual and footer
    lines = [
        line
        for line in after.strip().split("\n")
        if line.strip() and not line.startswith("---") and "Generated by" not in line
    ]
    assert lines == []


# --- Sync writes AGENTS.md to repos ---


def test_sync_writes_agents_md(tmp_path: Path, monkeypatch):
    from nauro.store.registry import register_project

    repo = tmp_path / "repo"
    repo.mkdir()
    store = register_project("myproj", [repo])
    scaffold_project_store("myproj", store)
    monkeypatch.chdir(repo)

    result = runner.invoke(app, ["sync"])
    assert result.exit_code == 0

    agents_md = repo / "AGENTS.md"
    assert agents_md.exists()
    content = agents_md.read_text()
    assert "# AGENTS.md" in content
    assert "## Project: myproj" in content
    assert "## Nauro MCP Tools" in content
    assert "# Manual" in content


def test_sync_agents_md_carries_project_scope_without_h1_stutter(tmp_path: Path, monkeypatch):
    """A filled project.md body reaches AGENTS.md under "## Project: {name}".

    The file's own H1 is stripped by the L0 builder, so the payload must not
    stutter a "# myproj" heading directly under the section header.
    """
    from nauro.store.registry import register_project

    repo = tmp_path / "repo"
    repo.mkdir()
    store = register_project("myproj", [repo])
    scaffold_project_store("myproj", store)
    (store / "project.md").write_text(
        "# myproj\n\n**One-liner:** Ships the thing.\n## Goals\n- Ship v1\n"
    )
    monkeypatch.chdir(repo)

    result = runner.invoke(app, ["sync"])
    assert result.exit_code == 0

    content = (repo / "AGENTS.md").read_text()
    assert "## Project: myproj" in content
    assert "**One-liner:** Ships the thing." in content
    assert content.index("## Project: myproj") < content.index("**One-liner:** Ships the thing.")
    assert "\n# myproj" not in content


def test_sync_agents_md_omits_scaffold_project_placeholders(tmp_path: Path, monkeypatch):
    """A freshly scaffolded store must not leak project.md placeholder prompts."""
    from nauro.store.registry import register_project

    repo = tmp_path / "repo"
    repo.mkdir()
    store = register_project("myproj", [repo])
    scaffold_project_store("myproj", store)
    monkeypatch.chdir(repo)

    result = runner.invoke(app, ["sync"])
    assert result.exit_code == 0

    content = (repo / "AGENTS.md").read_text()
    assert "**One-liner:** [What this does" not in content
    assert "[Primary goal" not in content
    assert "[Who uses this and how" not in content
    assert "[Hard limits" not in content


def test_sync_multi_repo(tmp_path: Path, monkeypatch):
    from nauro.store.registry import register_project

    repo1 = tmp_path / "repo1"
    repo2 = tmp_path / "repo2"
    repo1.mkdir()
    repo2.mkdir()
    store = register_project("myproj", [repo1, repo2])
    scaffold_project_store("myproj", store)
    monkeypatch.chdir(repo1)

    result = runner.invoke(app, ["sync"])
    assert result.exit_code == 0

    assert (repo1 / "AGENTS.md").exists()
    assert (repo2 / "AGENTS.md").exists()
    assert "Updated AGENTS.md" in result.output


def test_sync_skips_missing_repo(tmp_path: Path, monkeypatch):
    from nauro.store.registry import register_project

    real_repo = tmp_path / "real"
    real_repo.mkdir()
    store = register_project("myproj", [real_repo, tmp_path / "nonexistent"])
    scaffold_project_store("myproj", store)
    monkeypatch.chdir(real_repo)

    result = runner.invoke(app, ["sync"])
    assert result.exit_code == 0

    assert (real_repo / "AGENTS.md").exists()
    assert not (tmp_path / "nonexistent" / "AGENTS.md").exists()
    assert "Warning" in result.output


def test_sync_preserves_manual_section(tmp_path: Path, monkeypatch):
    from nauro.store.registry import register_project

    repo = tmp_path / "repo"
    repo.mkdir()
    store = register_project("myproj", [repo])
    scaffold_project_store("myproj", store)

    # Pre-populate an AGENTS.md with a manual section
    (repo / "AGENTS.md").write_text("# AGENTS.md\n\nOld content\n\n# Manual\n\nKeep this note.\n")
    monkeypatch.chdir(repo)

    result = runner.invoke(app, ["sync"])
    assert result.exit_code == 0

    content = (repo / "AGENTS.md").read_text()
    assert "Keep this note." in content
    assert "Old content" not in content  # auto section was regenerated
