"""Tests for AGENTS.md generation and sync integration."""

from pathlib import Path

from typer.testing import CliRunner

from nauro.cli.main import app
from nauro.templates.agents_md import generate_agents_md, parse_manual_section
from nauro.templates.scaffolds import scaffold_project_store

runner = CliRunner()


# --- generate_agents_md ---


def test_generate_includes_all_sections():
    result = generate_agents_md("myproj", "State and decisions here")
    assert "# AGENTS.md" in result
    assert "Auto-generated by Nauro" in result
    assert "Do not edit above the Manual section" in result
    assert "## Project: myproj" in result
    assert "State and decisions here" in result
    assert "## Nauro MCP Tools" in result
    assert "get_context" in result
    assert "propose_decision" in result
    assert "flag_question" in result
    assert "update_state" in result
    assert "# Manual" in result
    assert "Generated by [Nauro]" in result


def test_generate_includes_behavioral_instructions():
    result = generate_agents_md("myproj", "payload")
    assert "When to use these tools" in result
    assert "Propose a decision" in result
    assert "Flag a question" in result
    assert "Update state" in result


def test_generate_with_manual_section():
    result = generate_agents_md("proj", "payload", manual_section="Use conventional commits.\n")
    assert "# Manual" in result
    assert "Use conventional commits." in result


def test_generate_without_manual_section():
    result = generate_agents_md("proj", "payload", manual_section=None)
    assert "# Manual\n" in result
    # After Manual header, only the footer remains
    idx = result.index("# Manual\n")
    after = result[idx + len("# Manual\n") :]
    assert "Generated by" in after
    # No other content between Manual and footer
    lines = [
        line
        for line in after.strip().split("\n")
        if line.strip() and not line.startswith("---") and "Generated by" not in line
    ]
    assert lines == []


# --- parse_manual_section ---


def test_parse_manual_section(tmp_path: Path):
    agents_md = tmp_path / "AGENTS.md"
    agents_md.write_text(
        "# AGENTS.md\n\nSome auto content\n\n# Manual\n\nRepo-specific notes here.\n"
    )
    result = parse_manual_section(agents_md)
    assert result == "Repo-specific notes here."


def test_parse_manual_section_multiline(tmp_path: Path):
    agents_md = tmp_path / "AGENTS.md"
    agents_md.write_text("# AGENTS.md\n\n# Manual\n\nLine 1\nLine 2\n\nLine 3\n")
    result = parse_manual_section(agents_md)
    assert "Line 1" in result
    assert "Line 3" in result


def test_parse_manual_section_missing_file(tmp_path: Path):
    result = parse_manual_section(tmp_path / "AGENTS.md")
    assert result is None


def test_parse_manual_section_no_marker(tmp_path: Path):
    agents_md = tmp_path / "AGENTS.md"
    agents_md.write_text("# AGENTS.md\n\nJust some content\n")
    result = parse_manual_section(agents_md)
    assert result is None


def test_parse_manual_section_empty(tmp_path: Path):
    agents_md = tmp_path / "AGENTS.md"
    agents_md.write_text("# AGENTS.md\n\n# Manual\n\n")
    result = parse_manual_section(agents_md)
    assert result is None


# --- Manual section preservation ---


def test_manual_section_preserved_across_regenerations(tmp_path: Path):
    agents_md = tmp_path / "AGENTS.md"
    manual_text = "Always use feature branches.\nRun tests before pushing."

    # First generation with manual section
    content1 = generate_agents_md("proj", "v1 payload", manual_section=manual_text)
    agents_md.write_text(content1)

    # Parse the manual section back out
    parsed = parse_manual_section(agents_md)
    assert parsed == manual_text

    # Second generation preserving the manual section
    content2 = generate_agents_md("proj", "v2 payload", manual_section=parsed)
    agents_md.write_text(content2)

    # Manual section still intact
    parsed2 = parse_manual_section(agents_md)
    assert parsed2 == manual_text
    assert "v2 payload" in content2


# --- Sync writes AGENTS.md to repos ---


def test_sync_writes_agents_md(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("NAURO_HOME", str(tmp_path))
    from nauro.store.registry import register_project

    repo = tmp_path / "repo"
    repo.mkdir()
    store = register_project("myproj", [repo])
    scaffold_project_store("myproj", store)
    monkeypatch.chdir(repo)

    result = runner.invoke(app, ["sync"])
    assert result.exit_code == 0

    agents_md = repo / "AGENTS.md"
    assert agents_md.exists()
    content = agents_md.read_text()
    assert "# AGENTS.md" in content
    assert "## Project: myproj" in content
    assert "## Nauro MCP Tools" in content
    assert "# Manual" in content


def test_sync_multi_repo(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("NAURO_HOME", str(tmp_path))
    from nauro.store.registry import register_project

    repo1 = tmp_path / "repo1"
    repo2 = tmp_path / "repo2"
    repo1.mkdir()
    repo2.mkdir()
    store = register_project("myproj", [repo1, repo2])
    scaffold_project_store("myproj", store)
    monkeypatch.chdir(repo1)

    result = runner.invoke(app, ["sync"])
    assert result.exit_code == 0

    assert (repo1 / "AGENTS.md").exists()
    assert (repo2 / "AGENTS.md").exists()
    assert "Updated AGENTS.md" in result.output


def test_sync_skips_missing_repo(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("NAURO_HOME", str(tmp_path))
    from nauro.store.registry import register_project

    real_repo = tmp_path / "real"
    real_repo.mkdir()
    store = register_project("myproj", [real_repo, tmp_path / "nonexistent"])
    scaffold_project_store("myproj", store)
    monkeypatch.chdir(real_repo)

    result = runner.invoke(app, ["sync"])
    assert result.exit_code == 0

    assert (real_repo / "AGENTS.md").exists()
    assert not (tmp_path / "nonexistent" / "AGENTS.md").exists()
    assert "Warning" in result.output


def test_sync_preserves_manual_section(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("NAURO_HOME", str(tmp_path))
    from nauro.store.registry import register_project

    repo = tmp_path / "repo"
    repo.mkdir()
    store = register_project("myproj", [repo])
    scaffold_project_store("myproj", store)

    # Pre-populate an AGENTS.md with a manual section
    (repo / "AGENTS.md").write_text("# AGENTS.md\n\nOld content\n\n# Manual\n\nKeep this note.\n")
    monkeypatch.chdir(repo)

    result = runner.invoke(app, ["sync"])
    assert result.exit_code == 0

    content = (repo / "AGENTS.md").read_text()
    assert "Keep this note." in content
    assert "Old content" not in content  # auto section was regenerated
