"""Claude Code CLAUDE.md bridge.

Claude Code reads CLAUDE.md and its @-imports but never reads AGENTS.md
natively, so Nauro's generated AGENTS.md silently never loads in an unwired
Claude Code session. This module closes that gap with an auto-written,
Nauro-owned, thin CLAUDE.md that does nothing but import AGENTS.md.

``ensure_claude_bridge`` rides the single AGENTS.md-write seam
(``regenerate_agents_md_for_project``), so every path that regenerates
AGENTS.md - setup, adopt, sync, init, attach, reconnect, note, and the MCP
write tools - also ensures the bridge; no command has to remember to call it.
Callers that surface AGENTS.md warnings (init, attach, reconnect, note,
questions) surface a bridge advisory, symlink refusal, or failure through that
same warn channel; the MCP write tools stay protocol-silent.

The write is additive and ownership-marked: a fresh repo gets a two-line
bridge (an HTML-comment ownership marker plus the ``@AGENTS.md`` import). An
existing CLAUDE.md is never modified - one that already imports AGENTS.md is
left silent, one that does not gets a non-blocking advisory naming the
one-line fix, and a symlinked or non-regular CLAUDE.md is refused or reported.
There is no overwrite escape hatch.

Ownership is the exact marker line at top level (not a mere substring match),
so a hand-written file that only mentions the token is foreign and never
touched. Teardown removes only the single validated top-level bridge span and
rewrites the remaining bytes verbatim, so a fenced copy in user content and
any invalid-UTF-8 user bytes survive byte-for-byte. The marker is deliberately
distinct from the legacy NAURO:START/END block the setup cleanup strips, so
the two writers can never oscillate.
"""

from __future__ import annotations

from collections.abc import Iterator
from enum import Enum, auto
from pathlib import Path

from nauro.cli.integrations.outcomes import BridgeKind, BridgeOutcome
from nauro.constants import CLAUDE_BRIDGE_MARKER, CLAUDE_MD
from nauro.store.write_safety import find_symlink

# The single context-visible token: Claude Code follows an ``@path`` import.
BRIDGE_IMPORT = "@AGENTS.md"

# The owned bridge, byte-for-byte. One HTML-comment ownership marker line
# (Claude Code strips HTML comments from context, but the bytes survive on
# disk for ownership and teardown detection) followed by the import Claude
# Code follows. ASCII only, ASCII hyphens - the generated-output convention.
BRIDGE_MARKER_LINE = (
    f"<!-- {CLAUDE_BRIDGE_MARKER}: auto-generated by Nauro. Imports AGENTS.md so "
    "Claude Code loads the shared project context (Claude Code does not read "
    "AGENTS.md natively). Managed by nauro; remove with 'nauro adopt --remove'. -->"
)
BRIDGE_CONTENT = f"{BRIDGE_MARKER_LINE}\n{BRIDGE_IMPORT}\n"

_BOM = "\ufeff"


class BridgeState(Enum):
    ABSENT = auto()
    OWNED = auto()
    FOREIGN_BRIDGED = auto()
    FOREIGN_UNBRIDGED = auto()
    SYMLINK = auto()


# ─── Markdown-aware scanning ─────────────────────────────────────────────────


def _fence_marker(line: str) -> tuple[str, int, bool] | None:
    """Classify a line as a code-fence delimiter.

    Returns ``(char, run_length, closes_only)`` when the line opens or closes a
    fenced code block, else None. A fence is a run of at least three backticks
    or tildes, indented no more than three spaces. ``closes_only`` is True when
    nothing but whitespace follows the run - the CommonMark condition a closing
    fence must meet (an opener may carry an info string). A backtick fence
    whose info string itself contains a backtick is not a fence at all
    (CommonMark, to avoid colliding with inline code spans); tildes are exempt.
    """
    indent = len(line) - len(line.lstrip(" "))
    if indent > 3:
        return None
    rest = line[indent:]
    for char in ("`", "~"):
        if rest.startswith(char * 3):
            run = len(rest) - len(rest.lstrip(char))
            info = rest[run:]
            if char == "`" and "`" in info:
                return None
            return char, run, info.strip() == ""
    return None


def _active_lines(lines: list[str]) -> Iterator[tuple[int, str]]:
    """Yield ``(index, line)`` for the lines that sit outside fenced blocks.

    A fence is closed only by the same delimiter character with a run at least
    as long as the opener (so a tilde fence never closes a backtick fence, and
    ``` never closes ````), matching real Markdown semantics.
    """
    in_fence = False
    fence_char = ""
    fence_len = 0
    for index, line in enumerate(lines):
        marker = _fence_marker(line)
        if in_fence:
            if (
                marker is not None
                and marker[0] == fence_char
                and marker[1] >= fence_len
                and marker[2]
            ):
                in_fence = False
            continue
        if marker is not None:
            in_fence = True
            fence_char, fence_len = marker[0], marker[1]
            continue
        yield index, line


def _strip_inline_code(line: str) -> str:
    """Drop backtick-delimited inline code spans, keeping the surrounding text.

    A code span opens with a run of N backticks and closes with a run of
    exactly N backticks (so ``@AGENTS.md`` in a double-backtick span is code,
    not a live import). An unmatched opener is literal text, kept as-is. Spans
    are resolved within a single line on purpose (see ``_has_live_import``).
    """
    out: list[str] = []
    i = 0
    n = len(line)
    while i < n:
        if line[i] != "`":
            out.append(line[i])
            i += 1
            continue
        run_end = i
        while run_end < n and line[run_end] == "`":
            run_end += 1
        run = run_end - i
        close = _find_backtick_run(line, run_end, run)
        if close is None:
            # Unmatched opener: the backticks are literal, not a code span.
            out.append(line[i:run_end])
            i = run_end
        else:
            # Skip the whole span, including its delimiters.
            i = close + run
    return "".join(out)


def _find_backtick_run(line: str, start: int, run: int) -> int | None:
    """Index of the next run of exactly ``run`` backticks at/after ``start``."""
    i = start
    n = len(line)
    while i < n:
        if line[i] != "`":
            i += 1
            continue
        j = i
        while j < n and line[j] == "`":
            j += 1
        if j - i == run:
            return i
        i = j
    return None


def _strip_bom(text: str) -> str:
    return text[1:] if text.startswith(_BOM) else text


def _is_owned(content: str) -> bool:
    """True iff the exact ownership marker line appears at top level."""
    return any(line == BRIDGE_MARKER_LINE for _, line in _active_lines(content.splitlines()))


def _has_live_import(content: str) -> bool:
    """True iff a live ``@AGENTS.md`` import appears at top level.

    The import counts only outside fenced code blocks and inline code spans -
    the spans Claude Code actually follows - and as a whitespace-delimited word
    so ``foo@AGENTS.md`` does not register. Inline spans are resolved per line;
    that bound is deliberate (scanner-safety-first), so an import on the second
    line of a multi-line span reads as live rather than being suppressed.
    """
    return any(
        BRIDGE_IMPORT in _strip_inline_code(line).split()
        for _, line in _active_lines(content.splitlines())
    )


def _classify(content: str) -> BridgeState:
    if _is_owned(content):
        return BridgeState.OWNED
    if _has_live_import(content):
        return BridgeState.FOREIGN_BRIDGED
    return BridgeState.FOREIGN_UNBRIDGED


# ─── Public API ──────────────────────────────────────────────────────────────


def detect_bridge_state(repo_path: Path) -> BridgeState:
    """Classify the repo's CLAUDE.md for bridge ownership and safety.

    Raises ``OSError`` on an unreadable or non-regular CLAUDE.md; callers that
    must not abort a loop go through ``ensure_claude_bridge`` /
    ``remove_claude_bridge``, which wrap those errors into a typed outcome.
    """
    if find_symlink(repo_path, CLAUDE_MD) is not None:
        return BridgeState.SYMLINK
    claude_md = repo_path / CLAUDE_MD
    if not claude_md.exists():
        return BridgeState.ABSENT
    return _classify(_read_for_scan(claude_md))


def ensure_claude_bridge(repo_path: Path) -> BridgeOutcome:
    """Write the owned bridge when absent; never modify a non-owned CLAUDE.md.

    ABSENT writes the bridge; OWNED keeps it (preserving any content the user
    appended); FOREIGN_BRIDGED is a silent no-op; FOREIGN_UNBRIDGED returns a
    non-blocking advisory; a symlinked CLAUDE.md is refused; and any per-repo
    filesystem error (a directory at the path, an unreadable file) is caught
    and reported so a multi-repo loop continues.
    """
    refusal = find_symlink(repo_path, CLAUDE_MD)
    if refusal is not None:
        return BridgeOutcome(BridgeKind.REFUSED_SYMLINK, repo_path, refusal=refusal)
    claude_md = repo_path / CLAUDE_MD
    try:
        if not claude_md.exists():
            claude_md.write_text(BRIDGE_CONTENT, encoding="utf-8")
            return BridgeOutcome(BridgeKind.WROTE, repo_path)
        if not claude_md.is_file():
            return BridgeOutcome(
                BridgeKind.FAILED, repo_path, detail=f"{CLAUDE_MD} is not a regular file"
            )
        state = _classify(_read_for_scan(claude_md))
    except OSError as exc:
        return BridgeOutcome(BridgeKind.FAILED, repo_path, detail=str(exc))
    if state is BridgeState.OWNED:
        return BridgeOutcome(BridgeKind.KEPT, repo_path)
    if state is BridgeState.FOREIGN_BRIDGED:
        return BridgeOutcome(BridgeKind.FOREIGN_PRESENT, repo_path)
    return BridgeOutcome(BridgeKind.ADVISORY, repo_path)


def remove_claude_bridge(repo_path: Path) -> BridgeOutcome:
    """Remove the owned bridge on teardown, gated on the exact marker line.

    A file that is only the bridge is unlinked; a bridge the user appended to
    keeps the user's content byte-for-byte (invalid UTF-8 and CRLF included)
    and strips only the single validated top-level marker span and its
    associated import (tolerating blank lines between them). A CLAUDE.md
    without the marker line is left untouched; a symlink is refused; and a
    per-repo filesystem error is caught and reported so a loop continues.
    """
    refusal = find_symlink(repo_path, CLAUDE_MD)
    if refusal is not None:
        return BridgeOutcome(BridgeKind.REFUSED_SYMLINK, repo_path, refusal=refusal)
    claude_md = repo_path / CLAUDE_MD
    try:
        if not claude_md.exists():
            return BridgeOutcome(BridgeKind.NOTHING_TO_REMOVE, repo_path)
        if not claude_md.is_file():
            return BridgeOutcome(
                BridgeKind.FAILED, repo_path, detail=f"{CLAUDE_MD} is not a regular file"
            )
        # surrogateescape round-trips arbitrary bytes losslessly, so user
        # content that is not valid UTF-8 is rewritten byte-faithfully rather
        # than corrupted with U+FFFD. Only a leading BOM (on the marker line
        # that gets removed) is dropped.
        content = _strip_bom(claude_md.read_bytes().decode("utf-8", errors="surrogateescape"))
        if not _is_owned(content):
            return BridgeOutcome(BridgeKind.NOTHING_TO_REMOVE, repo_path)
        remaining = _strip_bridge_region(content)
        if remaining.strip() == "":
            claude_md.unlink()
            return BridgeOutcome(BridgeKind.REMOVED, repo_path)
        claude_md.write_bytes(remaining.encode("utf-8", errors="surrogateescape"))
        return BridgeOutcome(BridgeKind.STRIPPED, repo_path)
    except OSError as exc:
        return BridgeOutcome(BridgeKind.FAILED, repo_path, detail=str(exc))


# ─── internals ───────────────────────────────────────────────────────────────


def _read_for_scan(claude_md: Path) -> str:
    """Read a CLAUDE.md for classification, tolerant of bad bytes and a BOM.

    Newlines are irrelevant to classification, so text-mode reading is fine
    here; the byte-preserving read lives in the removal path.
    """
    return _strip_bom(claude_md.read_text(encoding="utf-8", errors="replace"))


def _strip_bridge_region(content: str) -> str:
    """Return ``content`` with the single top-level bridge span removed.

    The removed span is the first top-level marker line - the one that made the
    file OWNED - through its associated ``@AGENTS.md`` import, tolerating blank
    lines between them; a marker with no following import drops only the marker
    line. A marker or import quoted inside a fenced code block is not top level
    and survives. Line terminators are kept, so all other bytes are preserved.
    """
    segments = content.splitlines(keepends=True)
    bodies = [_body(s) for s in segments]
    marker_idx = next(
        (index for index, line in _active_lines(bodies) if line == BRIDGE_MARKER_LINE), None
    )
    if marker_idx is None:
        # Caller verified ownership; defensively leave the file untouched.
        return content
    end = marker_idx
    probe = marker_idx + 1
    while probe < len(segments) and bodies[probe].strip() == "":
        probe += 1
    if probe < len(segments) and bodies[probe].strip() == BRIDGE_IMPORT:
        end = probe
    return "".join(segments[:marker_idx] + segments[end + 1 :])


def _body(segment: str) -> str:
    """A kept-terminator line segment without its trailing newline."""
    return segment.rstrip("\r\n")
