"""Claude Code CLAUDE.md bridge.

Claude Code reads CLAUDE.md and its @-imports but never AGENTS.md, so a generated
AGENTS.md silently never loads. Nauro writes a thin, owned CLAUDE.md that imports it.

``ensure_claude_bridge`` rides the single AGENTS.md-write seam, so every path that
regenerates AGENTS.md ensures the bridge. CLI callers surface an advisory, a symlink
refusal, or a failure through their AGENTS.md warn channel; MCP write tools stay silent.

The write is additive and there is no overwrite hatch: an existing CLAUDE.md is never
modified, one that already imports AGENTS.md is silent, one that does not gets a
non-blocking advisory, and a symlinked or non-regular file is refused. Ownership is the
exact top-level marker line, and teardown removes only that validated span, rewriting
the rest verbatim so fenced copies and invalid-UTF-8 bytes survive.
"""

from __future__ import annotations

from collections.abc import Iterator
from enum import Enum, auto
from pathlib import Path

from nauro.cli.integrations.outcomes import BridgeKind, BridgeOutcome
from nauro.constants import CLAUDE_BRIDGE_MARKER, CLAUDE_MD
from nauro.store.write_safety import find_symlink

# The single context-visible token: Claude Code follows an ``@path`` import.
BRIDGE_IMPORT = "@AGENTS.md"

# The owned bridge, byte-for-byte. One HTML-comment ownership marker line
# (Claude Code strips HTML comments from context, but the bytes survive on
# disk for ownership and teardown detection) followed by the import Claude
# Code follows. ASCII only, ASCII hyphens - the generated-output convention.
BRIDGE_MARKER_LINE = (
    f"<!-- {CLAUDE_BRIDGE_MARKER}: auto-generated by Nauro. Imports AGENTS.md so "
    "Claude Code loads the shared project context (Claude Code does not read "
    "AGENTS.md natively). Managed by nauro; remove with 'nauro adopt --remove'. -->"
)
BRIDGE_CONTENT = f"{BRIDGE_MARKER_LINE}\n{BRIDGE_IMPORT}\n"

_BOM = "\ufeff"


class BridgeState(Enum):
    ABSENT = auto()
    OWNED = auto()
    FOREIGN_BRIDGED = auto()
    FOREIGN_UNBRIDGED = auto()
    SYMLINK = auto()


# ─── Markdown-aware scanning ─────────────────────────────────────────────────


def _fence_marker(line: str) -> tuple[str, int, bool] | None:
    """Classify a line as a code-fence delimiter.

    Returns ``(char, run_length, closes_only)`` when the line opens or closes a
    fenced code block, else None. A fence is a run of at least three backticks
    or tildes, indented no more than three spaces. ``closes_only`` is True when
    nothing but whitespace follows the run - the CommonMark condition a closing
    fence must meet (an opener may carry an info string). A backtick fence
    whose info string itself contains a backtick is not a fence at all
    (CommonMark, to avoid colliding with inline code spans); tildes are exempt.
    """
    indent = len(line) - len(line.lstrip(" "))
    if indent > 3:
        return None
    rest = line[indent:]
    for char in ("`", "~"):
        if rest.startswith(char * 3):
            run = len(rest) - len(rest.lstrip(char))
            info = rest[run:]
            if char == "`" and "`" in info:
                return None
            return char, run, info.strip() == ""
    return None


def _active_lines(lines: list[str]) -> Iterator[tuple[int, str]]:
    """Yield ``(index, line)`` for the lines that sit outside fenced blocks.

    A fence is closed only by the same delimiter character with a run at least
    as long as the opener (so a tilde fence never closes a backtick fence, and
    ``` never closes ````), matching real Markdown semantics.
    """
    in_fence = False
    fence_char = ""
    fence_len = 0
    for index, line in enumerate(lines):
        marker = _fence_marker(line)
        if in_fence:
            if (
                marker is not None
                and marker[0] == fence_char
                and marker[1] >= fence_len
                and marker[2]
            ):
                in_fence = False
            continue
        if marker is not None:
            in_fence = True
            fence_char, fence_len = marker[0], marker[1]
            continue
        yield index, line


def _strip_inline_code(line: str) -> str:
    """Drop backtick-delimited inline code spans, keeping the surrounding text.

    A code span opens with a run of N backticks and closes with a run of
    exactly N backticks (so ``@AGENTS.md`` in a double-backtick span is code,
    not a live import). An unmatched opener is literal text, kept as-is. Spans
    are resolved within a single line on purpose (see ``_has_live_import``).
    """
    out: list[str] = []
    i = 0
    n = len(line)
    while i < n:
        if line[i] != "`":
            out.append(line[i])
            i += 1
            continue
        run_end = i
        while run_end < n and line[run_end] == "`":
            run_end += 1
        run = run_end - i
        close = _find_backtick_run(line, run_end, run)
        if close is None:
            # Unmatched opener: the backticks are literal, not a code span.
            out.append(line[i:run_end])
            i = run_end
        else:
            # Skip the whole span, including its delimiters.
            i = close + run
    return "".join(out)


def _find_backtick_run(line: str, start: int, run: int) -> int | None:
    """Index of the next run of exactly ``run`` backticks at/after ``start``."""
    i = start
    n = len(line)
    while i < n:
        if line[i] != "`":
            i += 1
            continue
        j = i
        while j < n and line[j] == "`":
            j += 1
        if j - i == run:
            return i
        i = j
    return None


def _strip_bom(text: str) -> str:
    return text[1:] if text.startswith(_BOM) else text


def _is_owned(content: str) -> bool:
    """True iff the exact ownership marker line appears at top level."""
    return any(line == BRIDGE_MARKER_LINE for _, line in _active_lines(content.splitlines()))


def _has_live_import(content: str) -> bool:
    """True iff a live ``@AGENTS.md`` import appears at top level.

    The import counts only outside fenced code blocks and inline code spans -
    the spans Claude Code actually follows - and as a whitespace-delimited word
    so ``foo@AGENTS.md`` does not register. Inline spans are resolved per line;
    that bound is deliberate (scanner-safety-first), so an import on the second
    line of a multi-line span reads as live rather than being suppressed.
    """
    return any(
        BRIDGE_IMPORT in _strip_inline_code(line).split()
        for _, line in _active_lines(content.splitlines())
    )


def _classify(content: str) -> BridgeState:
    if _is_owned(content):
        return BridgeState.OWNED
    if _has_live_import(content):
        return BridgeState.FOREIGN_BRIDGED
    return BridgeState.FOREIGN_UNBRIDGED


# ─── Public API ──────────────────────────────────────────────────────────────


def detect_bridge_state(repo_path: Path) -> BridgeState:
    """Classify the repo's CLAUDE.md for bridge ownership and safety.
    Raises ``OSError`` on an unreadable or non-regular file; the ensure and remove wrappers turn
    that into a typed outcome so a multi-repo loop continues.
    """
    if find_symlink(repo_path, CLAUDE_MD) is not None:
        return BridgeState.SYMLINK
    claude_md = repo_path / CLAUDE_MD
    if not claude_md.exists():
        return BridgeState.ABSENT
    return _classify(_read_for_scan(claude_md))


def ensure_claude_bridge(repo_path: Path) -> BridgeOutcome:
    """Write the owned bridge when absent; never modify a non-owned CLAUDE.md.
    OWNED is kept with any appended user content, FOREIGN_BRIDGED is silent, FOREIGN_UNBRIDGED
    returns an advisory, a symlink is refused, and a filesystem error is reported not raised.
    """
    refusal = find_symlink(repo_path, CLAUDE_MD)
    if refusal is not None:
        return BridgeOutcome(BridgeKind.REFUSED_SYMLINK, repo_path, refusal=refusal)
    claude_md = repo_path / CLAUDE_MD
    try:
        if not claude_md.exists():
            claude_md.write_text(BRIDGE_CONTENT, encoding="utf-8")
            return BridgeOutcome(BridgeKind.WROTE, repo_path)
        if not claude_md.is_file():
            return BridgeOutcome(
                BridgeKind.FAILED, repo_path, detail=f"{CLAUDE_MD} is not a regular file"
            )
        state = _classify(_read_for_scan(claude_md))
    except OSError as exc:
        return BridgeOutcome(BridgeKind.FAILED, repo_path, detail=str(exc))
    if state is BridgeState.OWNED:
        return BridgeOutcome(BridgeKind.KEPT, repo_path)
    if state is BridgeState.FOREIGN_BRIDGED:
        return BridgeOutcome(BridgeKind.FOREIGN_PRESENT, repo_path)
    return BridgeOutcome(BridgeKind.ADVISORY, repo_path)


def remove_claude_bridge(repo_path: Path) -> BridgeOutcome:
    """Remove the owned bridge on teardown, gated on the exact marker line.
    A file that is only the bridge is unlinked; appended user content survives byte-for-byte with
    just the marker span stripped. No marker means untouched, and a symlink is refused.
    """
    refusal = find_symlink(repo_path, CLAUDE_MD)
    if refusal is not None:
        return BridgeOutcome(BridgeKind.REFUSED_SYMLINK, repo_path, refusal=refusal)
    claude_md = repo_path / CLAUDE_MD
    try:
        if not claude_md.exists():
            return BridgeOutcome(BridgeKind.NOTHING_TO_REMOVE, repo_path)
        if not claude_md.is_file():
            return BridgeOutcome(
                BridgeKind.FAILED, repo_path, detail=f"{CLAUDE_MD} is not a regular file"
            )
        # surrogateescape round-trips arbitrary bytes losslessly, so user
        # content that is not valid UTF-8 is rewritten byte-faithfully rather
        # than corrupted with U+FFFD. Only a leading BOM (on the marker line
        # that gets removed) is dropped.
        content = _strip_bom(claude_md.read_bytes().decode("utf-8", errors="surrogateescape"))
        if not _is_owned(content):
            return BridgeOutcome(BridgeKind.NOTHING_TO_REMOVE, repo_path)
        remaining = _strip_bridge_region(content)
        if remaining.strip() == "":
            claude_md.unlink()
            return BridgeOutcome(BridgeKind.REMOVED, repo_path)
        claude_md.write_bytes(remaining.encode("utf-8", errors="surrogateescape"))
        return BridgeOutcome(BridgeKind.STRIPPED, repo_path)
    except OSError as exc:
        return BridgeOutcome(BridgeKind.FAILED, repo_path, detail=str(exc))


# ─── internals ───────────────────────────────────────────────────────────────


def _read_for_scan(claude_md: Path) -> str:
    """Read a CLAUDE.md for classification, tolerant of bad bytes and a BOM.
    Newlines are irrelevant to classification; the byte-preserving read lives in the removal path.
    """
    return _strip_bom(claude_md.read_text(encoding="utf-8", errors="replace"))


def _strip_bridge_region(content: str) -> str:
    """Return ``content`` with the single top-level bridge span removed.
    The span runs from the first top-level marker line to its ``@AGENTS.md`` import, blank lines
    tolerated; a marker inside a fence survives, and every other byte is kept verbatim.
    """
    segments = content.splitlines(keepends=True)
    bodies = [_body(s) for s in segments]
    marker_idx = next(
        (index for index, line in _active_lines(bodies) if line == BRIDGE_MARKER_LINE), None
    )
    if marker_idx is None:
        # Caller verified ownership; defensively leave the file untouched.
        return content
    end = marker_idx
    probe = marker_idx + 1
    while probe < len(segments) and bodies[probe].strip() == "":
        probe += 1
    if probe < len(segments) and bodies[probe].strip() == BRIDGE_IMPORT:
        end = probe
    return "".join(segments[:marker_idx] + segments[end + 1 :])


def _body(segment: str) -> str:
    """A kept-terminator line segment without its trailing newline."""
    return segment.rstrip("\r\n")
