#!/usr/bin/env python3
"""Extract the nauro_core symbols a consumer repository imports.

The hosted MCP server lives in a private repository and imports nauro_core
submodule symbols directly, far past the curated ``nauro_core.__all__``. This
script reads that consumer's source with ``ast`` and writes the dotted name of
every imported symbol to a manifest, so nauro-core's own test suite can guard
the surface without depending on the private code.

Both module-level and function-local imports count, because a deferred import
binds the same symbol. Paths under a directory named ``tests`` are skipped: a
consumer's test-only import is not a production dependency. Relative imports are
ignored; only absolute ``nauro_core`` imports are part of the surface.

Usage: hosted_consumer_symbols.py [--out PATH] DIR...
Exits 0 when the manifest is written, 2 on a usage error.
"""

from __future__ import annotations

import argparse
import ast
import subprocess
import sys
from collections.abc import Iterator
from pathlib import Path

ROOT_PACKAGE = "nauro_core"
SKIPPED_DIR = "tests"
DEFAULT_OUT = Path("packages/nauro-core/tests/hosted_consumer_symbols.txt")


def iter_source_files(root: Path) -> Iterator[Path]:
    """Yield every Python file under root, skipping any path inside a tests directory."""
    for path in sorted(root.rglob("*.py")):
        if SKIPPED_DIR not in path.relative_to(root).parts:
            yield path


def _is_root_package(module: str) -> bool:
    return module == ROOT_PACKAGE or module.startswith(f"{ROOT_PACKAGE}.")


def imported_symbols(tree: ast.AST) -> Iterator[str]:
    """Yield the dotted nauro_core names bound by any import in the tree."""
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            if node.level or node.module is None or not _is_root_package(node.module):
                continue
            for alias in node.names:
                if alias.name != "*":
                    yield f"{node.module}.{alias.name}"
        elif isinstance(node, ast.Import):
            for alias in node.names:
                if _is_root_package(alias.name):
                    yield alias.name


def collect_symbols(roots: list[Path]) -> list[str]:
    """Return the sorted unique nauro_core names imported anywhere under the roots."""
    found: set[str] = set()
    for root in roots:
        for path in iter_source_files(root):
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
            found.update(imported_symbols(tree))
    return sorted(found)


def _git(directory: Path, *args: str) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(directory), *args],
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def describe_source(directory: Path) -> str:
    """Return a repo-relative label for the directory, with its commit when git knows one."""
    resolved = directory.resolve()
    toplevel = _git(resolved, "rev-parse", "--show-toplevel")
    if toplevel is None:
        return resolved.as_posix()
    repo = Path(toplevel)
    label = Path(repo.name, resolved.relative_to(repo)).as_posix()
    commit = _git(resolved, "rev-parse", "--short", "HEAD")
    return label if commit is None else f"{label} at {commit}"


def render_manifest(roots: list[Path], symbols: list[str]) -> str:
    """Return the manifest text: a two-line provenance header, then one name per line."""
    sources = ", ".join(describe_source(root) for root in roots)
    header = (
        f"# nauro_core symbols imported by a consumer repository: {sources}",
        "# Generated by scripts/hosted_consumer_symbols.py. Do not edit by hand.",
    )
    return "\n".join((*header, *symbols)) + "\n"


def build_parser() -> argparse.ArgumentParser:
    """Return the command-line parser for the consumer-symbol extractor."""
    parser = argparse.ArgumentParser(description="Extract consumed nauro_core symbols.")
    parser.add_argument("dirs", nargs="+", type=Path, help="consumer source directories")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="manifest path to write")
    return parser


def main(argv: list[str]) -> int:
    """Scan the requested directories and write the symbol manifest."""
    args = build_parser().parse_args(argv[1:])
    for directory in args.dirs:
        if not directory.is_dir():
            print(f"error: scan path does not exist: {directory}", file=sys.stderr)
            return 2
    symbols = collect_symbols(args.dirs)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_manifest(args.dirs, symbols), encoding="utf-8")
    print(f"Wrote {len(symbols)} symbol(s) to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
