"""AGENTS.md generation templates.

AGENTS.md is the cross-tool distribution layer — a single markdown file
placed at the repo root that any AI coding agent can read to understand
the project context. It is regenerated on `nauro sync`.

Convention: no Jinja2 — use f-strings and string templates only.
"""

from datetime import UTC, datetime
from pathlib import Path

from nauro.constants import AGENTS_MD, MANUAL_SECTION_HEADER

FOOTER_MARKER = "*Generated by [Nauro](https://nauro.dev)"


def generate_agents_md(
    project_name: str,
    l0_payload: str,
    manual_section: str | None = None,
) -> str:
    """Generate complete AGENTS.md content.

    Args:
        project_name: Name of the Nauro project.
        l0_payload: L0 context payload from build_l0_payload.
        manual_section: Preserved manual section content, or None.

    Returns:
        Complete AGENTS.md file content.
    """
    timestamp = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

    parts = [
        f"# AGENTS.md\n"
        f"<!-- Auto-generated by Nauro ({timestamp}). -->\n"
        "<!-- Do not edit above the Manual section —"
        " changes will be overwritten on next `nauro sync`. -->\n",
    ]

    # L0 payload
    parts.append(f"## Project: {project_name}\n\n{l0_payload}\n")

    # MCP tools and behavioral instructions
    parts.append(
        "## Nauro MCP Tools\n\n"
        "If your tool supports MCP, these 11 tools are available:\n\n"
        "**Read tools (6):**\n"
        "- `get_context(project, level)` — L0 summary, L1 working set, L2 full dump\n"
        "- `get_raw_file(project, path)` — raw content of any store file\n"
        "- `list_decisions(project, limit, include_superseded)` — browse decision history\n"
        "- `get_decision(project, number)` — full content of a specific decision\n"
        "- `diff_since_last_session(project, days)` — what changed since last session\n"
        "- `search_decisions(project, query, limit)` — keyword search across decisions\n\n"
        "**Write tools (5):**\n"
        "- `propose_decision(project, title, rationale, ...)` — propose a decision for validation\n"
        "- `confirm_decision(confirm_id)` — confirm a validated decision\n"
        "- `check_decision(proposed_approach)` — check for conflicts without writing\n"
        "- `flag_question(project, question, context)` — flag an open question\n"
        "- `update_state(project, delta)` — report what was completed\n\n"
        "### When to use these tools\n\n"
        "**Propose a decision** when you choose between approaches, replace or remove a\n"
        "dependency, establish a new pattern, or cut something from scope. Include\n"
        "what was rejected and why. Log at the moment the decision is made, not at\n"
        "the end of the session. Use `check_decision` first for advisory conflict checks.\n\n"
        "**Flag a question** when you encounter an unresolved ambiguity that a human\n"
        "should weigh in on — architectural trade-offs, unclear requirements, or\n"
        "scope boundaries.\n\n"
        "**Update state** when you complete a meaningful unit of work — a feature,\n"
        "a refactor, a bug fix — so the next session starts with current context.\n"
    )

    # Manual section
    parts.append(MANUAL_SECTION_HEADER + "\n")
    if manual_section:
        parts.append(manual_section.rstrip("\n") + "\n")

    # Attribution footer
    parts.append(
        "---\n"
        "*Generated by [Nauro](https://nauro.dev) — project context for agentic development.*\n"
    )

    return "\n".join(parts)


def regenerate_agents_md_for_project(project_key: str, store_path: Path) -> list[Path]:
    """Regenerate AGENTS.md in all repos associated with a project.

    Args:
        project_key: Either a v2 project_id (ULID) or a v1 project name.
            v2 takes priority — the v1 name lookup is the legacy fallback.
        store_path: Path to the project store directory.

    Returns:
        List of repo paths where AGENTS.md was updated.
    """
    from nauro.mcp.payloads import build_l0_payload
    from nauro.store.registry import (
        RegistrySchemaError,
        get_project_v2,
        load_registry,
    )

    repo_paths: list[str] = []
    display_name = project_key

    try:
        v2_entry = get_project_v2(project_key)
    except RegistrySchemaError:
        v2_entry = None
    if v2_entry is not None:
        repo_paths = list(v2_entry.get("repo_paths", []))
        display_name = v2_entry.get("name", project_key)
    else:
        registry = load_registry()
        entry = registry["projects"].get(project_key, {})
        repo_paths = list(entry.get("repo_paths", []))

    l0_payload = build_l0_payload(store_path)
    updated = []

    for repo_str in repo_paths:
        repo_path = Path(repo_str)
        if not repo_path.is_dir():
            continue
        agents_md_path = repo_path / AGENTS_MD
        manual = parse_manual_section(agents_md_path)
        content = generate_agents_md(display_name, l0_payload, manual_section=manual)
        agents_md_path.write_text(content)
        updated.append(repo_path)

    return updated


def parse_manual_section(agents_md_path: Path) -> str | None:
    """Read an existing AGENTS.md and extract everything below '# Manual'.

    Args:
        agents_md_path: Path to the AGENTS.md file.

    Returns:
        Content below the '# Manual' heading, or None if the file doesn't
        exist or has no Manual section.
    """
    if not agents_md_path.exists():
        return None

    content = agents_md_path.read_text()
    marker = "\n" + MANUAL_SECTION_HEADER + "\n"
    idx = content.find(marker)
    if idx == -1:
        # Also check if file starts with it
        if content.startswith(MANUAL_SECTION_HEADER + "\n"):
            section = content[len(MANUAL_SECTION_HEADER + "\n") :]
        else:
            return None
    else:
        section = content[idx + len(marker) :]

    # Strip the Nauro footer if present so it doesn't accumulate
    footer_idx = section.find(FOOTER_MARKER)
    if footer_idx != -1:
        # Also strip the --- line before the footer
        before_footer = section[:footer_idx].rstrip()
        if before_footer.endswith("---"):
            before_footer = before_footer[:-3]
        section = before_footer

    stripped = section.strip()
    return stripped if stripped else None
