"""AGENTS.md generation templates.

AGENTS.md is the cross-tool distribution layer — a single markdown file
placed at the repo root that any AI coding agent can read to understand
the project context. It is regenerated on `nauro sync`.

Convention: no Jinja2 — use f-strings and string templates only.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from nauro_core.constants import MCP_INSTRUCTIONS_STATIC

from nauro.constants import AGENTS_MD, MANUAL_SECTION_HEADER, SKILLS_SECTION_HEADER
from nauro.store.reader import read_text_lenient
from nauro.store.write_safety import find_symlink

# Prefix shared by every auto-generated attribution footer. Match by prefix
# (not by full canonical URL) so a stale footer from an earlier tagline cycle
# is recognized as auto-generated and not absorbed into the preserved manual
# section on the next regen.
FOOTER_MARKER = "*Generated by [Nauro]("
HEADER_MARKER = "<!-- Auto-generated by Nauro ("

# AGENTS.md MCP tool catalog — the single source of truth for both the rendered
# tool lists and the section counts ("Read tools (N)" / "Write tools (M)").
# Adding or moving a tool here automatically updates the displayed counts.
READ_TOOL_ROWS: list[tuple[str, str]] = [
    ("get_context(project, level)", "L0 summary, L1 working set, L2 full dump"),
    ("get_raw_file(project, path)", "raw content of any store file"),
    ("list_decisions(project, limit, include_superseded)", "browse decision history"),
    ("get_decision(project, number)", "full content of a specific decision"),
    ("diff_since_last_session(project, days)", "what changed since last session"),
    ("search_decisions(project, query, limit)", "keyword search across decisions"),
    ("check_decision(proposed_approach)", "surface related decisions without writing"),
]

WRITE_TOOL_ROWS: list[tuple[str, str]] = [
    ("propose_decision(project, title, rationale, ...)", "record a decision (single-call commit)"),
    ("flag_question(project, question, context)", "flag an open question"),
    ("update_state(project, delta)", "report what was completed"),
]


def _render_tool_rows(rows: list[tuple[str, str]]) -> str:
    return "\n".join(f"- `{sig}` - {desc}" for sig, desc in rows)


@dataclass
class PreservedSections:
    """Sections of AGENTS.md preserved across regen.

    ``order`` records the source order of the headers (subset of
    ``["skills", "manual"]``) so regen can re-emit them in the same order.
    Missing sections are absent from ``order``.
    """

    skills: str | None = None
    manual: str | None = None
    order: list[str] = field(default_factory=list)


def generate_agents_md(
    project_name: str,
    l0_payload: str,
    manual_section: str | None = None,
    *,
    project_id: str | None = None,
    skills_section: str | None = None,
    section_order: list[str] | None = None,
) -> str:
    """Generate complete AGENTS.md content.

    Args:
        project_name: Name of the Nauro project.
        l0_payload: L0 context payload from build_l0_payload.
        manual_section: Preserved manual section content, or None.
        project_id: v2 project id (ULID). When set, the store-routing block
            tells agents which id to pass; omitted for legacy v1 projects.
        skills_section: Preserved ``## Skills`` content, or None to omit.
        section_order: Order in which to emit preserved sections — list of
            ``"skills"`` and/or ``"manual"``. Defaults to source-appearance
            order when both are present (skills first, then manual).

    Returns:
        Complete AGENTS.md file content.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    parts = [
        f"# AGENTS.md\n"
        f"<!-- Auto-generated by Nauro ({timestamp}). -->\n"
        "<!-- Do not edit above the Manual section -"
        " changes will be overwritten on next `nauro sync`. -->\n",
    ]

    parts.append(MCP_INSTRUCTIONS_STATIC + "\n")
    # Reaches sessions the local MCP server never wired into: a fresh clone
    # ships this committed file but no live server, so name the single command
    # that self-routes the rest of setup.
    parts.append(
        "If you have no Nauro MCP tools in this session (no `mcp__nauro__*` tools "
        "available), tell the user this repository uses Nauro to share project decisions "
        "across agents and suggest they run 'nauro status'. If the 'nauro' command is not "
        "installed, install it with 'uv tool install nauro'.\n"
    )
    parts.append(f"## Project: {project_name}\n\n{l0_payload}\n")

    # Store-routing block. This file lives in the working copy, so any agent
    # reading it is on a machine with the local store — where the stdio server
    # is the canonical transport (it resolves the store from this repo and
    # pulls remote changes on startup). Steer agents to the local tools so a
    # separately-mounted cloud connector under the same name does not capture
    # calls to the wrong store.
    project_id_line = (
        f"Pass `project_id: {project_id}` on calls that accept it. " if project_id else ""
    )
    parts.append(
        "## Nauro store for this repo\n\n"
        "This repo's Nauro store is served locally. Use the `mcp__nauro__*` tools "
        "(the local stdio server). "
        f"{project_id_line}"
        "If a cloud Nauro connector (e.g. `mcp__claude_ai_Nauro__*`) is also mounted, "
        "prefer the local `mcp__nauro__*` tools for this repo - they read the working "
        "copy on this machine.\n\n"
        "Connector naming: if you use the bundled `@nauro-*` Claude Code subagents, "
        "name the cloud connector exactly `Nauro`, because those subagents reference "
        "the `mcp__claude_ai_Nauro__*` tools by that name and a different name leaves "
        "them unresolved. Other tools (Codex, Cursor) can use any connector name, as "
        "long as it differs from a local stdio `nauro` entry.\n"
    )

    # MCP tools and behavioral instructions. Counts are derived from the
    # row catalogs above so they can never drift from the rendered lists.
    read_count = len(READ_TOOL_ROWS)
    write_count = len(WRITE_TOOL_ROWS)
    total_count = read_count + write_count
    parts.append(
        f"## Nauro MCP Tools\n\n"
        f"If your tool supports MCP, these {total_count} tools are available; "
        f"without MCP, the same tools work as `nauro <tool-name>` shell commands "
        f"(e.g. `nauro check-decision`).\n\n"
        f"**Read tools ({read_count}):**\n"
        f"{_render_tool_rows(READ_TOOL_ROWS)}\n\n"
        f"**Write tools ({write_count}):**\n"
        f"{_render_tool_rows(WRITE_TOOL_ROWS)}\n\n"
        "### When to use these tools\n\n"
        "**Flag a question** when you encounter an unresolved ambiguity that a human\n"
        "should weigh in on - architectural trade-offs, unclear requirements, or\n"
        "scope boundaries.\n\n"
        "**Update state** when you complete a meaningful unit of work - a feature,\n"
        "a refactor, a bug fix - so the next session starts with current context.\n"
        "\n"
        "**Keep public-facing artifacts public.** Paraphrase Nauro rationale instead of\n"
        "citing raw decision or question ids. Internal planning and review may cite ids.\n"
    )

    # Preserved sections in source-appearance order.
    order = (
        section_order
        if section_order is not None
        else _default_section_order(skills_section is not None)
    )
    for section in order:
        if section == "skills" and skills_section is not None:
            parts.append(SKILLS_SECTION_HEADER + "\n\n" + skills_section.rstrip("\n") + "\n")
        elif section == "manual":
            block = MANUAL_SECTION_HEADER + "\n"
            if manual_section:
                block += "\n" + manual_section.rstrip("\n") + "\n"
            parts.append(block)

    parts.append(
        "---\n"
        "*Generated by [Nauro](https://nauro.ai) from human-ratified project "
        "judgment shared with every connected AI agent.*\n"
    )

    return "\n".join(parts)


def _default_section_order(has_skills: bool) -> list[str]:
    """When no explicit order is provided, emit skills before manual."""
    out: list[str] = []
    if has_skills:
        out.append("skills")
    # Always include manual block (its absence is fine — emits empty header).
    out.append("manual")
    return out


def agents_md_is_safe_to_replace(agents_md_path: Path) -> bool:
    if agents_md_path.is_symlink():
        return False
    if not agents_md_path.exists():
        return True
    if not agents_md_path.is_file():
        return False
    content = read_text_lenient(agents_md_path)
    return HEADER_MARKER in content and FOOTER_MARKER in content


def regenerate_agents_md_for_project(
    project_key: str,
    store_path: Path,
    *,
    overwrite_unmanaged: bool = False,
) -> list[Path]:
    """Regenerate AGENTS.md in all repos associated with a project.

    Args:
        project_key: Either a v2 project_id (ULID) or a v1 project name.
            v2 takes priority — the v1 name lookup is the legacy fallback.
        store_path: Path to the project store directory.
        overwrite_unmanaged: Replace an existing AGENTS.md even when Nauro
            did not generate it. Off by default: only ``nauro sync`` passes
            True, every other caller preserves hand-written files.

    Returns:
        List of repo paths where AGENTS.md was updated.
    """
    from nauro.mcp.payloads import build_l0_payload
    from nauro.store.registry import (
        RegistrySchemaError,
        get_project_v2,
        get_repo_paths,
    )

    display_name = project_key
    project_id: str | None = None

    try:
        v2_entry = get_project_v2(project_key)
    except RegistrySchemaError:
        v2_entry = None
    if v2_entry is not None:
        display_name = v2_entry.get("name", project_key)
        project_id = project_key  # v2 registry is id-keyed

    repo_paths = get_repo_paths(project_key)
    l0_payload = build_l0_payload(store_path)
    updated = []

    for repo_str in repo_paths:
        repo_path = Path(repo_str)
        if not repo_path.is_dir():
            continue
        # Never write through a pre-planted symlink, regardless of
        # overwrite_unmanaged; warn_then_regen surfaces the refusal.
        if find_symlink(repo_path, AGENTS_MD) is not None:
            continue
        agents_md_path = repo_path / AGENTS_MD
        if not overwrite_unmanaged and not agents_md_is_safe_to_replace(agents_md_path):
            continue
        preserved = parse_preserved_sections(agents_md_path)
        content = generate_agents_md(
            display_name,
            l0_payload,
            manual_section=preserved.manual,
            project_id=project_id,
            skills_section=preserved.skills,
            section_order=preserved.order or None,
        )
        agents_md_path.write_text(content, encoding="utf-8")
        updated.append(repo_path)

    return updated


def remove_generated_agents_md(repo_path: Path) -> str | None:
    """Remove a Nauro-generated ``AGENTS.md`` from ``repo_path`` on teardown.

    The inverse of ``regenerate_agents_md_for_project`` for ``--remove`` paths,
    written to never destroy user content:

    - No file, or a file Nauro did not generate (no generator footer): left
      untouched, returns ``None``.
    - Generated by Nauro but carrying a non-empty ``# Manual`` section (user
      notes preserved across regen): the generated payload is stripped and the
      file is rewritten to just the user's ``# Manual`` section, so no stale
      "use Nauro MCP" instructions survive a teardown. The ``## Skills`` section
      is Nauro-managed and is dropped.
    - Generated by Nauro with no manual notes: unlinked, status line returned.

    Returns a one-line status string (indented for ``setup_all_surfaces``) when
    it acted, else ``None``.
    """
    refusal = find_symlink(repo_path, AGENTS_MD)
    if refusal is not None:
        return f"  {repo_path}: {refusal.message}"
    agents_md_path = repo_path / AGENTS_MD
    if not agents_md_path.exists():
        return None
    if FOOTER_MARKER not in read_text_lenient(agents_md_path):
        # Not a Nauro-generated file (or hand-rewritten past recognition); leave it.
        return None
    manual = parse_preserved_sections(agents_md_path).manual
    if manual:
        # Keep the user's notes, drop everything Nauro generated (payload,
        # store-routing, skills, footer) so nothing points at the removed server.
        agents_md_path.write_text(
            f"{MANUAL_SECTION_HEADER}\n\n{manual.rstrip()}\n", encoding="utf-8"
        )
        return f"  {repo_path}: stripped generated AGENTS.md, kept your # Manual section"
    agents_md_path.unlink()
    return f"  {repo_path}: removed generated AGENTS.md"


def parse_preserved_sections(agents_md_path: Path) -> PreservedSections:
    """Parse ``## Skills`` and ``# Manual`` sections from an existing AGENTS.md.

    Both sections are preserved across regen. ``order`` records source-
    appearance order so regen re-emits them in the same order the user had.
    """
    if not agents_md_path.exists():
        return PreservedSections()

    content = read_text_lenient(agents_md_path)
    skills_idx = _find_header(content, SKILLS_SECTION_HEADER)
    manual_idx = _find_header(content, MANUAL_SECTION_HEADER)

    skills = (
        _extract_section_body(content, skills_idx, SKILLS_SECTION_HEADER, MANUAL_SECTION_HEADER)
        if skills_idx != -1
        else None
    )
    manual = (
        _extract_section_body(content, manual_idx, MANUAL_SECTION_HEADER, SKILLS_SECTION_HEADER)
        if manual_idx != -1
        else None
    )

    # Order reflects sections that actually contain content. An empty `# Manual`
    # body (always-emitted from generate_agents_md when no content) is treated
    # as absent — round-trip stability when the user has no manual notes.
    candidates: list[tuple[str, int]] = []
    if skills is not None:
        candidates.append(("skills", skills_idx))
    if manual is not None:
        candidates.append(("manual", manual_idx))
    candidates.sort(key=lambda x: x[1])
    order = [name for name, _ in candidates]

    return PreservedSections(skills=skills, manual=manual, order=order)


def _find_header(content: str, header: str) -> int:
    """Return the start index of ``header`` at line start, or -1."""
    if content.startswith(header + "\n"):
        return 0
    idx = content.find("\n" + header + "\n")
    return -1 if idx == -1 else idx + 1


def _extract_section_body(
    content: str, header_idx: int, header: str, other_header: str
) -> str | None:
    """Return the body text following ``header`` until the other header or footer."""
    body_start = header_idx + len(header + "\n")
    rest = content[body_start:]

    candidates: list[int] = []
    other_marker = "\n" + other_header + "\n"
    other_pos = rest.find(other_marker)
    if other_pos != -1:
        candidates.append(other_pos)
    footer_pos = rest.find(FOOTER_MARKER)
    if footer_pos != -1:
        candidates.append(footer_pos)

    end = min(candidates) if candidates else len(rest)
    section = rest[:end].rstrip()
    while section.endswith("---"):
        section = section[:-3].rstrip()
    section = section.strip()
    return section if section else None
