"""AGENTS.md generation templates.

AGENTS.md is the cross-tool distribution layer — a single markdown file
placed at the repo root that any AI coding agent can read to understand
the project context. It is regenerated on `nauro sync`.

Convention: no Jinja2 — use f-strings and string templates only.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

# Underscore alias, not the public APPROVAL_BEFORE_PROPOSE name: the public
# re-export landed after the current nauro-core floor (>=1.5.0), so switching
# is gated on raising the floor to nauro-core>=1.6.0 at the next release.
from nauro_core.protocol import _APPROVAL_BEFORE_PROPOSE

from nauro.constants import AGENTS_MD, MANUAL_SECTION_HEADER, SKILLS_SECTION_HEADER
from nauro.store.reader import read_text_lenient
from nauro.store.write_safety import find_symlink

if TYPE_CHECKING:
    from nauro.cli.integrations.outcomes import BridgeOutcome

# Prefix shared by every auto-generated attribution footer. Match by prefix
# (not by full canonical URL) so a stale footer from an earlier tagline cycle
# is recognized as auto-generated and not absorbed into the preserved manual
# section on the next regen.
FOOTER_MARKER = "*Generated by [Nauro]("
HEADER_MARKER = "<!-- Auto-generated by Nauro ("

# Condensed protocol digest rendered instead of the full
# MCP_INSTRUCTIONS_STATIC block: MCP-connected sessions already receive that
# block verbatim via initialize.instructions, so this file carries only the
# two rules a session without MCP must not lose - the check_decision
# preflight and the human-approval gate before propose_decision. The approval
# fragment stays verbatim (a no-MCP session can reach `nauro
# propose-decision`, a single-call commit, via shell, so the human-authority
# boundary must survive here word for word).
PROTOCOL_DIGEST = (
    "Nauro carries human-ratified project judgment across agent sessions: "
    "surface relevant prior judgment before choosing an approach, and record "
    "only decisions the user approves.\n"
    "\n"
    "Before responding to any technical change request - architecture, "
    "library choice, API design, data model, infrastructure, a vendor swap - "
    "call `check_decision` with the proposal, even when you intend to push "
    "back or refuse. It surfaces related decisions with their triage headers "
    "inline, without judging conflicts; before proposing, read the ones you "
    "reason about in full with `get_decision`.\n"
    "\n"
    # The fragment no longer names the write call, so this surface supplies
    # the anchor: without MCP the boundary applies to `nauro propose-decision`.
    f"Before `propose_decision` (or `nauro propose-decision`): "
    f"{_APPROVAL_BEFORE_PROPOSE}\n"
)


# Rendered in AGENTS.md only: the shared static block sits at its 1,635-char
# truncation budget (MCP_INSTRUCTIONS_STATIC_MAX_CHARS in the nauro-core
# constants tests), so it cannot carry this section.
EVIDENCE_RIDER_SECTION = (
    "## When to record outcome evidence\n"
    "\n"
    "When the world tests an existing decision, propose an update rider on it: "
    "an exception is approved against it, an incident traces back to it, it "
    "survives a real test, or it stops mattering. Open the rider with a dated "
    "evidence marker, `*Evidence (<type>, <date>):*`, with types exception, "
    "held, pain, and obsolete. The rider goes through the same draft-and-approve "
    "flow as any proposal.\n"
)


@dataclass
class PreservedSections:
    """Sections of AGENTS.md preserved across regen.

    ``order`` records the source order of the headers (subset of
    ``["skills", "manual"]``) so regen can re-emit them in the same order.
    Missing sections are absent from ``order``.
    """

    skills: str | None = None
    manual: str | None = None
    order: list[str] = field(default_factory=list)


def generate_agents_md(
    project_name: str,
    l0_payload: str,
    manual_section: str | None = None,
    *,
    project_id: str | None = None,
    skills_section: str | None = None,
    section_order: list[str] | None = None,
) -> str:
    """Generate complete AGENTS.md content.

    Args:
        project_name: Name of the Nauro project.
        l0_payload: L0 context payload from build_l0_payload.
        manual_section: Preserved manual section content, or None.
        project_id: Project id (ULID). When set, the store-routing block
            tells agents which id to pass.
        skills_section: Preserved ``## Skills`` content, or None to omit.
        section_order: Order in which to emit preserved sections — list of
            ``"skills"`` and/or ``"manual"``. Defaults to source-appearance
            order when both are present (skills first, then manual).

    Returns:
        Complete AGENTS.md file content.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    parts = [
        f"# AGENTS.md\n"
        f"<!-- Auto-generated by Nauro ({timestamp}). -->\n"
        "<!-- Do not edit above the Manual section -"
        " changes will be overwritten on next `nauro sync`. -->\n",
    ]

    parts.append(PROTOCOL_DIGEST)
    # Reaches sessions the local MCP server never wired into: a fresh clone
    # ships this committed file but no live server, so name the single command
    # that self-routes the rest of setup.
    parts.append(
        "If you have no Nauro MCP tools in this session (no `mcp__nauro__*` tools "
        "available), tell the user this repository uses Nauro to share project decisions "
        "across agents and suggest they run 'nauro status'. If the 'nauro' command is not "
        "installed, install it with 'uv tool install nauro'.\n"
    )
    parts.append(EVIDENCE_RIDER_SECTION)
    # The L0 payload below is byte-identical to `get_context` at L0, so a
    # session that already holds this file can skip that call.
    parts.append(
        "This file embeds the project's L0 context payload, byte-identical to "
        "`get_context` at L0: when AGENTS.md is already in context, skip the "
        "L0 call and use L1/L2 or `diff_since_last_session` for deeper or "
        "fresher context.\n"
    )
    parts.append(f"## Project: {project_name}\n\n{l0_payload}\n")

    # Store-routing block. This file lives in the working copy, so any agent
    # reading it is on a machine with the local store — where the stdio server
    # is the canonical transport (it resolves the store from this repo and
    # pulls remote changes on startup). Steer agents to the local tools so a
    # separately-mounted cloud connector under the same name does not capture
    # calls to the wrong store.
    project_id_line = (
        f"Pass `project_id: {project_id}` on calls that accept it. " if project_id else ""
    )
    parts.append(
        "## Nauro store for this repo\n\n"
        "This repo's Nauro store is served locally. Use the `mcp__nauro__*` tools "
        "(the local stdio server). "
        f"{project_id_line}"
        "If a cloud Nauro connector (e.g. `mcp__claude_ai_Nauro__*`) is also mounted, "
        "prefer the local `mcp__nauro__*` tools for this repo - they read the working "
        "copy on this machine.\n\n"
        "Connector naming: if you use the bundled `@nauro-*` Claude Code subagents, "
        "name the cloud connector exactly `Nauro`, because those subagents reference "
        "the `mcp__claude_ai_Nauro__*` tools by that name and a different name leaves "
        "them unresolved. Other tools (Codex, Cursor) can use any connector name, as "
        "long as it differs from a local stdio `nauro` entry.\n"
    )

    # Tool catalog collapsed to a pointer: MCP sessions get signatures and
    # per-tool guidance from tools/list, and MCP-less agents reach the CLI
    # mirror via `nauro --help`, so the file names the mirror rule instead of
    # restating ten signatures. The public-artifacts rule stays: AGENTS.md is
    # its only delivery surface.
    parts.append(
        "## Nauro MCP Tools\n\n"
        "Nauro's 10 tools are available over MCP; without MCP, the same tools "
        "work as `nauro <tool-name>` shell commands (underscores become "
        "hyphens, e.g. `nauro check-decision`). Run `nauro --help` for the "
        "full list.\n\n"
        "**Keep public-facing artifacts public.** Paraphrase Nauro rationale instead of\n"
        "citing raw decision or question ids. Internal planning and review may cite ids.\n"
    )

    # Preserved sections in source-appearance order.
    order = (
        section_order
        if section_order is not None
        else _default_section_order(skills_section is not None)
    )
    for section in order:
        if section == "skills" and skills_section is not None:
            parts.append(SKILLS_SECTION_HEADER + "\n\n" + skills_section.rstrip("\n") + "\n")
        elif section == "manual":
            block = MANUAL_SECTION_HEADER + "\n"
            if manual_section:
                block += "\n" + manual_section.rstrip("\n") + "\n"
            parts.append(block)

    parts.append(
        "---\n"
        "*Generated by [Nauro](https://nauro.ai) from human-ratified project "
        "judgment shared with every connected AI agent.*\n"
    )

    return "\n".join(parts)


def _default_section_order(has_skills: bool) -> list[str]:
    """When no explicit order is provided, emit skills before manual."""
    out: list[str] = []
    if has_skills:
        out.append("skills")
    # Always include manual block (its absence is fine — emits empty header).
    out.append("manual")
    return out


def _mask_header_timestamp(content: str) -> str:
    """Blank the auto-generated header timestamp line for content comparison.

    A managed file whose only difference from a fresh regen is the header
    timestamp carries no new information; masking the line on both sides
    lets regen detect that and skip the write, keeping bytes and mtime
    stable for prompt caches. Only meaningful for files that carry the
    marker line: the caller must gate on HEADER_MARKER presence, because
    masking maps a marker line and a blank line to the same value, so an
    unmanaged file could otherwise mask equal to generated content.
    """
    return "\n".join("" if line.startswith(HEADER_MARKER) else line for line in content.split("\n"))


def agents_md_is_safe_to_replace(agents_md_path: Path) -> bool:
    if agents_md_path.is_symlink():
        return False
    if not agents_md_path.exists():
        return True
    if not agents_md_path.is_file():
        return False
    content = read_text_lenient(agents_md_path)
    return HEADER_MARKER in content and FOOTER_MARKER in content


def regenerate_agents_md_for_project(
    project_key: str,
    store_path: Path,
    *,
    overwrite_unmanaged: bool = False,
    bridge_sink: list[BridgeOutcome] | None = None,
) -> list[Path]:
    """Regenerate AGENTS.md in all repos associated with a project.

    Args:
        project_key: The project_id (ULID) whose registry entry lists the
            associated repos.
        store_path: Path to the project store directory.
        overwrite_unmanaged: Replace an existing AGENTS.md even when Nauro
            did not generate it. Off by default: only ``nauro sync`` passes
            True, every other caller preserves hand-written files.
        bridge_sink: When provided, the ``BridgeOutcome`` for each repo whose
            AGENTS.md was written is appended here, in the same order as the
            returned repo list. The Claude Code bridge is ensured regardless of
            this argument — it rides every AGENTS.md write so no path forgets
            it; the sink only lets a caller surface the outcome.

    Returns:
        List of repo paths where AGENTS.md was updated. Repos whose existing
        file already matches the regenerated content (ignoring the header
        timestamp) are skipped and not listed.
    """
    from nauro.cli.integrations.claude_bridge import ensure_claude_bridge
    from nauro.mcp.payloads import build_l0_payload
    from nauro.store.registry import (
        RegistrySchemaError,
        get_project_v2,
        get_repo_paths,
    )

    display_name = project_key
    project_id: str | None = None

    try:
        v2_entry = get_project_v2(project_key)
    except RegistrySchemaError:
        v2_entry = None
    if v2_entry is not None:
        display_name = v2_entry.get("name", project_key)
        project_id = project_key  # v2 registry is id-keyed

    repo_paths = get_repo_paths(project_key)
    l0_payload = build_l0_payload(store_path)
    updated = []

    for repo_str in repo_paths:
        repo_path = Path(repo_str)
        if not repo_path.is_dir():
            continue
        # Never write through a pre-planted symlink, regardless of
        # overwrite_unmanaged; warn_then_regen surfaces the refusal.
        if find_symlink(repo_path, AGENTS_MD) is not None:
            continue
        agents_md_path = repo_path / AGENTS_MD
        if not overwrite_unmanaged and not agents_md_is_safe_to_replace(agents_md_path):
            continue
        preserved = parse_preserved_sections(agents_md_path)
        content = generate_agents_md(
            display_name,
            l0_payload,
            manual_section=preserved.manual,
            project_id=project_id,
            skills_section=preserved.skills,
            section_order=preserved.order or None,
        )
        # Content-conditional write: a managed file identical modulo the
        # header timestamp means no store change reached it, so skip the
        # rewrite and keep the existing bytes (and timestamp) stable. Gated
        # on the marker line so an unmanaged file always falls through to
        # the write: masking blanks the marker line, so without the gate a
        # file missing only the marker would wrongly mask equal and never
        # be reclaimed. The bridge below stays write-coupled, so a skipped
        # repo is neither reported as updated nor re-bridged.
        if agents_md_path.is_file():
            existing = read_text_lenient(agents_md_path)
            if HEADER_MARKER in existing and _mask_header_timestamp(
                existing
            ) == _mask_header_timestamp(content):
                continue
        agents_md_path.write_text(content, encoding="utf-8")
        updated.append(repo_path)
        # The Claude Code bridge rides the AGENTS.md write: this is the single
        # seam every regen path funnels through, so the bridge is ensured for
        # setup, adopt, sync, init, attach, note, and the MCP write tools alike.
        # ensure_claude_bridge never raises; a per-repo failure is a typed
        # outcome so this loop always completes.
        bridge_outcome = ensure_claude_bridge(repo_path)
        if bridge_sink is not None:
            bridge_sink.append(bridge_outcome)

    return updated


def remove_generated_agents_md(repo_path: Path) -> str | None:
    """Remove a Nauro-generated ``AGENTS.md`` from ``repo_path`` on teardown.

    The inverse of ``regenerate_agents_md_for_project`` for ``--remove`` paths,
    written to never destroy user content:

    - No file, or a file Nauro did not generate (no generator footer): left
      untouched, returns ``None``.
    - Generated by Nauro but carrying a non-empty ``# Manual`` section (user
      notes preserved across regen): the generated payload is stripped and the
      file is rewritten to just the user's ``# Manual`` section, so no stale
      "use Nauro MCP" instructions survive a teardown. The ``## Skills`` section
      is Nauro-managed and is dropped.
    - Generated by Nauro with no manual notes: unlinked, status line returned.

    Returns a one-line status string (indented for ``setup_all_surfaces``) when
    it acted, else ``None``.
    """
    refusal = find_symlink(repo_path, AGENTS_MD)
    if refusal is not None:
        return f"  {repo_path}: {refusal.message}"
    agents_md_path = repo_path / AGENTS_MD
    if not agents_md_path.exists():
        return None
    if FOOTER_MARKER not in read_text_lenient(agents_md_path):
        # Not a Nauro-generated file (or hand-rewritten past recognition); leave it.
        return None
    manual = parse_preserved_sections(agents_md_path).manual
    if manual:
        # Keep the user's notes, drop everything Nauro generated (payload,
        # store-routing, skills, footer) so nothing points at the removed server.
        agents_md_path.write_text(
            f"{MANUAL_SECTION_HEADER}\n\n{manual.rstrip()}\n", encoding="utf-8"
        )
        return f"  {repo_path}: stripped generated AGENTS.md, kept your # Manual section"
    agents_md_path.unlink()
    return f"  {repo_path}: removed generated AGENTS.md"


def parse_preserved_sections(agents_md_path: Path) -> PreservedSections:
    """Parse ``## Skills`` and ``# Manual`` sections from an existing AGENTS.md.

    Both sections are preserved across regen. ``order`` records source-
    appearance order so regen re-emits them in the same order the user had.
    """
    if not agents_md_path.exists():
        return PreservedSections()

    content = read_text_lenient(agents_md_path)
    skills_idx = _find_header(content, SKILLS_SECTION_HEADER)
    manual_idx = _find_header(content, MANUAL_SECTION_HEADER)

    skills = (
        _extract_section_body(content, skills_idx, SKILLS_SECTION_HEADER, MANUAL_SECTION_HEADER)
        if skills_idx != -1
        else None
    )
    manual = (
        _extract_section_body(content, manual_idx, MANUAL_SECTION_HEADER, SKILLS_SECTION_HEADER)
        if manual_idx != -1
        else None
    )

    # Order reflects sections that actually contain content. An empty `# Manual`
    # body (always-emitted from generate_agents_md when no content) is treated
    # as absent — round-trip stability when the user has no manual notes.
    candidates: list[tuple[str, int]] = []
    if skills is not None:
        candidates.append(("skills", skills_idx))
    if manual is not None:
        candidates.append(("manual", manual_idx))
    candidates.sort(key=lambda x: x[1])
    order = [name for name, _ in candidates]

    return PreservedSections(skills=skills, manual=manual, order=order)


def _find_header(content: str, header: str) -> int:
    """Return the start index of ``header`` at line start, or -1."""
    if content.startswith(header + "\n"):
        return 0
    idx = content.find("\n" + header + "\n")
    return -1 if idx == -1 else idx + 1


def _extract_section_body(
    content: str, header_idx: int, header: str, other_header: str
) -> str | None:
    """Return the body text following ``header`` until the other header or footer."""
    body_start = header_idx + len(header + "\n")
    rest = content[body_start:]

    candidates: list[int] = []
    other_marker = "\n" + other_header + "\n"
    other_pos = rest.find(other_marker)
    if other_pos != -1:
        candidates.append(other_pos)
    footer_pos = rest.find(FOOTER_MARKER)
    if footer_pos != -1:
        candidates.append(footer_pos)

    end = min(candidates) if candidates else len(rest)
    section = rest[:end].rstrip()
    while section.endswith("---"):
        section = section[:-3].rstrip()
    section = section.strip()
    return section if section else None
